edl/sgx_time.edl, edl/sgx_tstd.edl, rust-sgx-sdk/common/inc/sys/epoll.h, rust-sgx-sdk/common/inc/sys/socket.h, rust-sgx-sdk/common/inc/sys/struct_timespec.h, rust-sgx-sdk/common/inc/sys/uio.h
=> Fix link error

enclave/Cargo.toml
https://github.com/baidu/rust-sgx-sdk/commit/515b47b1365dcd86d6c3e629f1658120929bc579
=> Fits new sgx_tcrypto_helper

client/Cargo.toml, client/src/lib.rs, client/src/main.rs, enclave/src/attestation.rs, enclave/src/tls.rs, substratee-node-calls/Cargo.toml, substratee-node-calls/src/lib.rs, worker/Cargo.toml, worker/src/main.rs
added some function calls to substrate-api-calls crate
=> Cl substratee node api

Cargo.lock, client/Cargo.toml, enclave/Cargo.lock, enclave/src/aes.rs, enclave/src/attestation.rs, enclave/src/cert.rs, enclave/src/ed25519.rs, enclave/src/hex.rs, enclave/src/io.rs, enclave/src/lib.rs, enclave/src/rsa3072.rs, enclave/src/state.rs, enclave/src/tls_ra.rs, enclave/src/utils.rs
- increase code quality: reduce duplicates, become more rust idiomatic closes #41 
- enclave: split code into multiple files
- hopefully removed all potential panics and unwraps: closes #37 
- added trait for Option<T> and Result<T> that unwraps or returns sgx_status_t::SGX_ERROR_UNEXPECTED: closes #39 
- mr_enclave_check: closes #47
=> Cl security hardening rebased

.githooks/pre-commit, Makefile
cargo fmt as git pre-commit hook. installation through `make githooks`
=> new target to install git hooks

Jenkinsfile, Makefile, README.md
with rust-sgx-sdk v1.1.1 and Intel SGX SDK v2.9
=> Use docker image for Jenkins

enclave/Cargo.lock, worker/src/enclave/api.rs, worker/src/main.rs, worker/src/tests/commons.rs, worker/src/tests/integration_tests.rs
* Fix: In integration tests pass the actual mrenclave to the `TrustedCallSigned` for correct verification in enclave
* update Cargo.lock
* small api-changes: stronger return types, renaming of functions for consistency
=> some-refactoring-and-fixing

Cargo.lock, Makefile, client/Cargo.toml, enclave/Cargo.lock, enclave/chain_relay/src/lib.rs, enclave/chain_relay/src/state.rs, enclave/src/lib.rs, substratee-node-calls/Cargo.toml, worker/Cargo.toml, worker/src/main.rs
* [enclave] relax condition to simpy emit a warning if there are still unincluded extrinsics by the enclave
* [chan_relay] include finalized blocks without finalization proof and simply keep track of them. A the moment there is no upper limit of blocks without proof.
=> Cl adjust chain relay

Cargo.lock, client/Cargo.toml, enclave/Cargo.lock, enclave/Cargo.toml, substratee-node-calls/Cargo.toml, worker/Cargo.toml
- use latest substrate-api-client
- update Cargo.lock files
=> use substrate-api-client v0.4.3-sub2.0.0-alpha.7

Cargo.lock, client/Cargo.toml, client/src/main.rs, enclave/Cargo.lock, enclave/Cargo.toml, enclave/Enclave.edl, enclave/chain_relay/src/lib.rs, enclave/src/constants.rs, enclave/src/io.rs, enclave/src/lib.rs, stf/src/lib.rs, stf/src/sgx.rs, substratee-node-calls/Cargo.toml, worker/Cargo.toml, worker/src/enclave/api.rs, worker/src/main.rs, worker/src/tests/commons.rs, worker/src/tests/integration_tests.rs, worker/src/tests/mod.rs
* chain_relay now scans blocks for unshield extrinsics and executes upon them.
=> perform-shieldfunds-upon-block-sync

Cargo.lock, client/Cargo.toml, client/src/main.rs, enclave/Cargo.lock, enclave/Cargo.toml, enclave/chain_relay/Cargo.toml, enclave/chain_relay/src/storage_proof.rs, enclave/src/lib.rs, enclave/src/rsa3072.rs, substratee-node-primitives/Cargo.toml, substratee-node-primitives/src/lib.rs, worker/Cargo.toml, worker/src/main.rs, worker/src/tests/commons.rs, worker/src/tests/integration_tests.rs, worker/worker-api/Cargo.toml
When retrieving storage values from within the enclave a readproof is passed into the enclave and checked. Closes #98
=> Cl readproof

enclave/Enclave.edl, enclave/chain_relay/src/lib.rs, enclave/chain_relay/src/state.rs, enclave/src/aes.rs, enclave/src/io.rs, enclave/src/lib.rs, enclave/src/tls_ra.rs, worker/src/enclave/api.rs, worker/src/main.rs
* Parse header digest to look for scheduled changes of authorities. Closes #109 
* Enable validator proof check upon chain_relay_initialization
* remove some false positive errors/warnings
=> Cl detect changing votersets

Jenkinsfile
Archive the signed enclave, the substratee-worker and the substratee-client
=> Jenkinsfile: Archive binaries

Cargo.lock, README.md, client/Cargo.toml, enclave/Cargo.lock, enclave/Cargo.toml, enclave/chain_relay/Cargo.toml, enclave/src/attestation.rs, enclave/src/constants.rs, enclave/src/lib.rs, stf/Cargo.toml, stf/src/sgx.rs, substratee-node-primitives/Cargo.toml, worker/Cargo.toml, worker/worker-api/Cargo.toml
=> upstream upgrade to 2.0.0-rc5

enclave/Cargo.lock, enclave/Cargo.toml, enclave/src/lib.rs, enclave/src/rpc/api.rs, enclave/src/rpc/author/client_error.rs, enclave/src/rpc/author/mod.rs, enclave/src/rpc/basic_pool.rs, enclave/src/rpc/error.rs, enclave/src/rpc/worker_api_direct.rs, enclave/src/top_pool/base_pool.rs, enclave/src/top_pool/error.rs, enclave/src/top_pool/future.rs, enclave/src/top_pool/listener.rs, enclave/src/top_pool/pool.rs, enclave/src/top_pool/primitives.rs, enclave/src/top_pool/ready.rs, enclave/src/top_pool/rotator.rs, enclave/src/top_pool/tracked_map.rs, enclave/src/top_pool/validated_pool.rs, enclave/src/top_pool/watcher.rs
Some top pool unit tests. Not yet complete. Rotator ban tests are failing.
Issue: How to track time in enclave.
=> Sidechain m8.2 unittesting

enclave/src/lib.rs, enclave/src/rpc/author/mod.rs, stf/src/sgx.rs, worker/src/main.rs
=> Sidechain m8.2 block production fix

client/src/main.rs, enclave/Enclave.edl, enclave/src/lib.rs, enclave/src/rpc/api.rs, enclave/src/top_pool/listener.rs, enclave/src/top_pool/pool.rs, enclave/src/top_pool/primitives.rs, enclave/src/top_pool/validated_pool.rs, enclave/src/top_pool/watcher.rs, stf/src/sgx.rs, substratee-worker-primitives/src/block.rs, substratee-worker-primitives/src/lib.rs, worker/src/enclave/api.rs, worker/src/enclave/worker_api_direct_server.rs, worker/src/main.rs
=> Return blockhash to watching client

enclave/src/attestation.rs
=> Attestation: Switch to new API version for RA

client/demo_direct_call.sh, client/demo_shielding_unshielding.sh, enclave/src/lib.rs
fix demos and nonce in shielding call
=> Shielding fix

enclave/src/tests.rs, stf/src/lib.rs, stf/src/sgx.rs
stf/src/sgx.rs root account funding
+ cargo fmt
=> Add root funds

Cargo.lock, Makefile, UpdateRustSGXSDK.mk, enclave/Cargo.lock, enclave/src/attestation.rs, rust-sgx-sdk/common/inc/dirent.h, rust-sgx-sdk/common/inc/sys/stat.h, rust-sgx-sdk/edl/intel/sgx_dcap_tvl.edl, rust-sgx-sdk/edl/sgx_sys.edl, rust-sgx-sdk/version
update rust sgx sdk to commit ed9e7cce4fd40efd7a256d5c4be1c5f00778a5bb
=> update rust sgx sdk

.github/workflows/build_and_test.yml, client/demo_shielding_unshielding.sh, enclave/Enclave.edl, enclave/src/attestation.rs, enclave/src/error.rs, enclave/src/lib.rs, enclave/src/rsa3072.rs, enclave/src/tls_ra.rs, local-setup/launch.py, local-setup/py/helpers.py, local-setup/py/worker.py, scripts/init_env.sh, scripts/m6.sh, scripts/m8.sh, worker/src/cli.yml, worker/src/enclave/tls_ra.rs, worker/src/main.rs
* This tests against an updated node with the rebranding incorporated. Hence, change 'SubstrateeRegistry' → `Teerex`.
* Add `skip-ra` flag to mutual-remote attestation procedure to be able to exchange keys with `SGX_MODE=SW`
* Add Some Error types to `enclave/rs3072`, which were used to debug.
* Supply `mrenclave` with mock_register_enclave extrinsic because the integration tests read the `mrenclave` from the registry.
* local-setup: Read config from file and minor improvements.
* Closes #302
* Closes #250
=> [GA] add M8 and M6 integration tests

Cargo.lock, enclave/Cargo.lock
Update to follow current integritee-node version
=> update to substrate commit df1165d7b47d43f7b5032512ad41ac8ab2ead117

Cargo.lock, Cargo.toml, enclave/Cargo.lock, enclave/Cargo.toml, enclave/src/lib.rs, primitives/worker/Cargo.toml, primitives/worker/src/block.rs, primitives/worker/src/lib.rs, primitives/worker/src/rpc.rs, stf/Cargo.toml, worker/rpc/server/src/mock.rs, worker/src/tests/commons.rs
=> cleanup substratee worker primitives

Cargo.lock, enclave/Cargo.lock, enclave/Cargo.toml, enclave/src/aes.rs, enclave/src/io.rs, enclave/src/lib.rs, enclave/src/state.rs, stf/src/stf_sgx.rs, stf/src/test_genesis.rs, worker/Cargo.toml
=> Bh hot fix

Cargo.lock, Cargo.toml, Makefile, enclave/Cargo.lock, enclave/Cargo.toml, enclave/src/aes.rs, enclave/src/attestation.rs, enclave/src/ed25519.rs, enclave/src/error.rs, enclave/src/io.rs, enclave/src/lib.rs, enclave/src/state.rs, enclave/src/tests.rs, enclave/src/tls_ra.rs, primitives/sgx/io/Cargo.toml, primitives/sgx/io/src/lib.rs
* extract io stuff to a separate crate and apply the changes to the code base.
This was preparatory work to extract the crypto stuff to a separate crate, but I preferred not to make this PR any bigger.
* Closes #355
=> Extract sgx-io out of the enclave

enclave/src/lib.rs, primitives/sidechain/primitives/src/traits/mod.rs, primitives/sidechain/primitives/src/types/block.rs
u64 is much simpler to handle.
=> [sidechain/primitives] change SidechainBlock.timestamp type to u64 + use millisecs as timestamp

.github/workflows/build_and_test.yml, Cargo.lock, enclave/Cargo.lock, primitives/settings/src/lib.rs, worker/src/main.rs
- Logic : if the default enclave pre-funding is smaller than the existential deposit, then it is set to MIN_FUND_INCREASE_FACTOR * existential deposit
=> make enclave pre-funding generic

app-libs/stf/src/lib.rs, app-libs/stf/src/test_genesis.rs, core-primitives/types/src/lib.rs, enclave-runtime/src/tests.rs
* mainly remove duplicate code and introduce some helper stuff
=> [enclave-runtime/tests] cleanup

.github/workflows/build_and_test.yml, Cargo.lock, app-libs/stf/Cargo.toml, app-libs/stf/src/lib.rs, app-libs/stf/src/stf_sgx.rs, core-primitives/settings/src/lib.rs, enclave-runtime/Cargo.lock
because worker didn't run with the last updated node (https://github.com/integritee-network/integritee-node/blob/078230aaa1604ffc503be81cc647f6a3a7360d64/runtime/src/lib.rs#L527-L528)
=> Change the id of teerex pallet and clean code

core-primitives/settings/src/lib.rs
related to #480 
Worker is now able to run more than one hour.
=> increases enclave funding 10x

.github/workflows/build_and_test.yml, core-primitives/settings/src/lib.rs, enclave-runtime/Cargo.lock
Follows the newest node update
closes #523
=> Update spec version to 4

core-primitives/stf-executor/src/executor.rs
Thanks to @suinuj for detecting this bug!
=> [parentchain pallet] save state permanently after mutation

.github/workflows/build_and_test.yml, core-primitives/settings/src/lib.rs
Follows the newest node update
Closes  #548
=> Update to spec version 5 and update CI to use new node

Cargo.lock, core-primitives/test/Cargo.toml, core-primitives/test/src/builders/mod.rs, core-primitives/test/src/builders/parentchain_block_builder.rs, core-primitives/test/src/builders/parentchain_header_builder.rs, core-primitives/test/src/mock/trusted_operation_pool_mock.rs, sidechain/consensus/aura/src/mock.rs
This is a cherry-pick from a larger PR of mine. @gaudenzkessler needs it for his PR #556 , to write unit test.
(cherry picked from commit 5584b5b71b47171ecd038857a016f601ab8e8b36)
(cherry picked from commit 5356fe65d11ef9f7eabfb7bbd8da90cf12e29be3)
=> Add unit test builder for parentchain blocks and headers

service/src/worker.rs
=> Remove thread creation from sidechain block gossiping

core-primitives/settings/src/lib.rs, local-setup/github-action-config.json, local-setup/simple-config.json, service/src/cli.yml, service/src/main.rs
- -- dev cli flag added
- print out the enclave account id if this has not enough fund
- bootstrap fund only if --dev flag
- stop the starting worker thread if not enough fund to register enclave
=> Alice is faucet only in dev mode

sidechain/consensus/aura/src/block_importer.rs, sidechain/consensus/aura/src/verifier.rs, sidechain/consensus/common/src/block_import.rs, sidechain/consensus/common/src/error.rs
part of #567
- adds import error handling function
- adds block ancestry mismatch error (there is no header, so I couldn't call it HeaderAncestryMismatch)
=> [sidechain] detect out of sync error

docs/README.md, docs/trusted-rpc-interface.md
Related issue : #431
- adds rpc related docs
- adds the links listed in issue #431
=> add rpc doc

Cargo.lock, cli/src/main.rs, core/rpc-client/Cargo.toml, core/rpc-client/src/direct_client.rs, core/rpc-client/src/mock.rs, enclave-runtime/Cargo.lock, enclave-runtime/Cargo.toml, enclave-runtime/src/rpc/worker_api_direct.rs
- rcp call
- print sgx metadata cli
=> RPC call to get metadata from sgx-runtime

Cargo.lock, enclave-runtime/src/test/sidechain_aura_tests.rs, enclave-runtime/src/tests.rs, sidechain/block-composer/src/block_composer.rs, sidechain/consensus/aura/src/block_importer.rs, sidechain/consensus/aura/src/lib.rs, sidechain/consensus/aura/src/test/block_importer_tests.rs, sidechain/consensus/aura/src/test/mocks/proposer_mock.rs, sidechain/consensus/aura/src/verifier.rs, sidechain/consensus/common/src/block_import.rs, sidechain/consensus/slots/src/slots.rs, sidechain/primitives/src/traits/mod.rs, sidechain/primitives/src/types/block.rs, sidechain/primitives/src/types/block_data.rs, sidechain/primitives/src/types/mod.rs, sidechain/storage/Cargo.toml, sidechain/storage/src/test_utils.rs, sidechain/test/src/lib.rs, sidechain/test/src/sidechain_block_builder.rs, sidechain/test/src/sidechain_block_data_builder.rs, sidechain/test/src/sidechain_header_builder.rs, sidechain/top-pool-executor/src/call_operator.rs
=> introduce layer for indirection for sidechainblock

core/parentchain/block-importer/src/block_importer.rs, core/parentchain/light-client/src/grandpa_light_validation.rs, core/parentchain/light-client/src/io.rs, core/parentchain/light-client/src/lib.rs, core/parentchain/light-client/src/mocks/validator_mock.rs
* Outsource grandpa light validation to separate module
closes #736
=> make Validation trait agnostic to finalization algorithm

core-primitives/settings/src/lib.rs, service/src/account_funding.rs, service/src/main.rs
=> Init of parachain light client

core-primitives/test/src/mock/onchain_mock.rs, core/parentchain/indirect-calls-executor/src/indirect_calls_executor.rs, enclave-runtime/src/test/fixtures/components.rs, enclave-runtime/src/test/sidechain_aura_tests.rs, enclave-runtime/src/test/top_pool_tests.rs, sidechain/consensus/aura/src/block_importer.rs, sidechain/consensus/aura/src/lib.rs, sidechain/consensus/aura/src/test/block_importer_tests.rs, sidechain/consensus/aura/src/test/fixtures/mod.rs, sidechain/consensus/aura/src/verifier.rs, sidechain/consensus/common/src/block_import.rs, sidechain/consensus/slots/src/lib.rs, sidechain/consensus/slots/src/mocks.rs, sidechain/consensus/slots/src/slots.rs, sidechain/validateer-fetch/src/validateer.rs
Replaces PR #777 
closes #750 :
- Slot claiming is now done with the authorities found according to the newly imported block (thanks to peeking before importing)
=> Update slot claiming strategy (rebased)

enclave-runtime/src/test/sidechain_aura_tests.rs, sidechain/consensus/aura/Cargo.toml, sidechain/consensus/aura/src/lib.rs, sidechain/consensus/aura/src/verifier.rs, sidechain/consensus/common/Cargo.toml, sidechain/consensus/slots/Cargo.toml, sidechain/consensus/slots/src/per_shard_slot_worker_tests.rs, sidechain/consensus/slots/src/slots.rs
Part of preparation for https://github.com/integritee-network/pallets/issues/58
=> Use slot methods from pallets

core-primitives/time-utils/src/lib.rs
=> Fix timing tests in time-utils

Cargo.lock, Cargo.toml, core-primitives/substrate-sgx/environmental/Cargo.toml, core-primitives/substrate-sgx/environmental/src/lib.rs, core-primitives/substrate-sgx/externalities/Cargo.toml, core-primitives/substrate-sgx/sp-io/Cargo.toml, core-primitives/substrate-sgx/sp-io/src/lib.rs, enclave-runtime/Cargo.lock
Hopefully fixes #803 and #932
Before: Worker crashed when running about 30 clients in parallel within under a minute.
Now: Running 60 clients in parallel for longer than 10 minutes, and worker has not crashed yet. So I believe this fixes the error:
Open question: Should I further investigate and try to write an integration (inside the enclave) that failed before and now passes? @clangenb
=> Use sgx_tstd thread local in environmental

cli/demo_smart_contract.sh
run the demo on localhost:
```
integritee-node purge-chain --dev
integritee-node --tmp --dev -lruntime=debug
export RUST_LOG=integritee_service=info,ita_stf=debug
integritee-service run
export RUST_LOG_LOG=integritee-cli=info,ita_stf=info
demo_smart_contract.sh -p <NODEPORT> -P <WORKERPORT>
```
=> Finalize EVM Smart contract demo

service/src/main.rs
- No block syn for teeracle: 
- Not needed: the teeracle only send an extrinsic to the node.
- Block sync means long time before the teeracle can update the values and the enclave has to pay uncessary fees.
- Call of init_light_client still needed, to initialize extrinsics_factory
=> Remove block syncing for Teeracle.

README.md, docs/trusted-rpc-interface.md
=> Updated links to the new gitbook.

Cargo.lock, app-libs/exchange-oracle/src/test.rs, core-primitives/node-api/metadata/src/metadata_mocks.rs, core-primitives/node-api/metadata/src/pallet_sidechain.rs, core/rest-client/src/http_client.rs, docker/docker-compose.yml, enclave-runtime/Cargo.lock, enclave-runtime/src/global_components.rs, enclave-runtime/src/initialization.rs, enclave-runtime/src/test/mocks/types.rs, enclave-runtime/src/test/sidechain_aura_tests.rs, enclave-runtime/src/test/tests_main.rs, enclave-runtime/src/top_pool_execution.rs, sidechain/block-composer/src/block_composer.rs, sidechain/consensus/aura/src/proposer_factory.rs, sidechain/consensus/aura/src/slot_proposer.rs, sidechain/consensus/common/Cargo.toml, sidechain/consensus/common/src/block_import.rs, sidechain/consensus/common/src/block_import_confirmation_handler.rs, sidechain/consensus/common/src/lib.rs, sidechain/consensus/common/src/peer_block_sync.rs, sidechain/consensus/common/src/test/mocks/confirm_block_import_mock.rs
closes #922
- updates docker image to `1.0.16`
=> Confirm sidechain blocks when importing instead of when proposing

Makefile
Compiles the build targets if any .rs or .toml file has changed
=> Compile cli anytime

sidechain/consensus/slots/src/lib.rs
The logging with the log level to ERROR will look like : 
- for the sidechain mode:
- for the offchain-worker mode:
There is no block sync for the Teeracle
=> Add sidechain block number to parentchain block sync output

README.md
@Niederb what was the reason for only putting this in the previous release branch and not on master?
=> [Readme] add section referring to the new gitbook

enclave-runtime/src/top_pool_execution.rs, sidechain/consensus/aura/src/lib.rs, sidechain/consensus/slots/src/lib.rs, sidechain/consensus/slots/src/mocks.rs
=> remove aura dev setting `allow_delayed_proposal`

core-primitives/top-pool/src/ready.rs, core-primitives/top-pool/src/tracked_map.rs
This PR aims to fix some minor clippy warnings.
=> Make clippy happy - TrackedMap

scripts/polkadot_update.sh
Maybe it makes sense to use it directly for the next update and improve on it.
=> Add polkadot_update.sh script

Cargo.lock, cli/src/base_cli/commands/listen.rs, cli/src/trusted_operation.rs, core/parentchain/indirect-calls-executor/src/indirect_calls_executor.rs, docker/docker-compose.yml, enclave-runtime/Cargo.lock, service/src/main.rs
closes #838 
change in the pallets: https://github.com/integritee-network/pallets/pull/92
=> Add block number to ProcessedParentchainBlock Event

core/parentchain/light-client/src/finality.rs, core/parentchain/light-client/src/justification.rs, core/parentchain/light-client/src/light_validation.rs, core/parentchain/light-client/src/light_validation_state.rs, core/parentchain/light-client/src/state.rs
This PR aims to do some simple refactors / renamings, nothing big (yet).
Fixes #432
=> Minor itc-light-client cleanup 

app-libs/stf/src/trusted_call.rs, core-primitives/node-api/metadata/src/metadata_mocks.rs, core-primitives/node-api/metadata/src/pallet_teerex.rs, docker/docker-compose.yml
=> Add a proof of execution to shield funds trusted call

core-primitives/settings/src/lib.rs, local-setup/py/worker.py, service/src/setup.rs
Remove some obsolete code after #1328
=> Remove remnants of `last_slot.bin`

service/Cargo.toml, service/src/main.rs, service/src/prometheus_metrics.rs
=> introduce attesteer compiler flag to avoid marblerun in pure dcap mode

.github/workflows/build_and_test.yml
Missing peace to https://github.com/integritee-network/worker/pull/1353
=> Added new tag pattern

.github/workflows/build_and_test.yml
The goal is to have a teeracle docker dcap version installed into Securitee infra.
=> Added dcap flag to teeracle #1191

samples/teeracle/README.md, samples/teeracle/install-teeracle.sh, samples/teeracle/kubernetes/Chart.yaml, samples/teeracle/kubernetes/templates/teeracle.yaml, samples/teeracle/kubernetes/values.yaml
The aim of this PR is to have a sample helm chart installation into Securitee's Kubernetes
=> Added teeracle helm chart sample #1360

service/Cargo.toml
=> attesteer feature implies dcap

enclave-runtime/src/attestation.rs
=> fix skip-ra with dcap

app-libs/stf/src/stf_sgx.rs, cli/test_shield_on_target_nodes_with_transfer_to_alice.sh, core-primitives/settings/src/lib.rs, core-primitives/types/src/parentchain.rs, core/parentchain/block-importer/src/block_importer.rs, core/parentchain/indirect-calls-executor/src/filter_metadata.rs, core/parentchain/light-client/src/io.rs, core/parentchain/light-client/src/light_validation.rs, enclave-runtime/src/error.rs, enclave-runtime/src/initialization/global_components.rs, enclave-runtime/src/initialization/mod.rs, enclave-runtime/src/initialization/parentchain/common.rs, enclave-runtime/src/initialization/parentchain/mod.rs, enclave-runtime/src/initialization/parentchain/target_b_parachain.rs, enclave-runtime/src/initialization/parentchain/target_b_solochain.rs, enclave-runtime/src/lib.rs, enclave-runtime/src/utils.rs, local-setup/config/three-nodes-one-worker.json, local-setup/py/worker.py, local-setup/tmux_logger_three_nodes.sh, service/src/cli.yml, service/src/config.rs, service/src/main.rs, service/src/ocall_bridge/bridge_api.rs, service/src/ocall_bridge/component_factory.rs, service/src/ocall_bridge/worker_on_chain_ocall.rs, service/src/parentchain_handler.rs, service/src/setup.rs, service/src/tests/commons.rs
Additionally, I added the `ParentchainId` to many log messages, as it was very hard to debug without that.
=> [Multiparentchain] add support for third parentchain `Target_B`

sidechain/consensus/common/src/block_import_queue_worker.rs
feel free to merge if you want
=> more functional code in block import

Cargo.lock, app-libs/sgx-runtime/Cargo.toml, app-libs/stf/Cargo.toml, cli/Cargo.toml, core-primitives/enclave-api/Cargo.toml, core-primitives/types/Cargo.toml, docker/README.md, enclave-runtime/Cargo.lock, enclave-runtime/Cargo.toml, service/Cargo.toml
=> bump sdk version to 0.13.0. add handy REDME docs

Cargo.lock, cli/Cargo.toml, enclave-runtime/Cargo.lock, enclave-runtime/Cargo.toml, service/Cargo.toml
the release of 0.13.0 ran incompletely. bumping to release again
=> bump version

cli/src/base_cli/commands/balance.rs, cli/src/base_cli/mod.rs, cli/src/trusted_base_cli/mod.rs
* log AccountData when printing free balance on L1
=> enhance cli

Cargo.lock, cli/Cargo.toml, cli/src/guess_the_number/commands/guess.rs, cli/src/guess_the_number/commands/push_by_one_day.rs, cli/src/guess_the_number/commands/set_winnings.rs, cli/src/trusted_base_cli/commands/add_session_proxy.rs, cli/src/trusted_base_cli/commands/nonce.rs, cli/src/trusted_base_cli/commands/note_bloat.rs, cli/src/trusted_base_cli/commands/transfer.rs, cli/src/trusted_base_cli/commands/unshield_funds.rs, cli/src/trusted_base_cli/commands/waste_time.rs, cli/src/trusted_command_utils.rs, enclave-runtime/Cargo.lock, enclave-runtime/Cargo.toml, service/Cargo.toml, sidechain/rpc-handler/src/direct_top_pool_api.rs
=> remove vulnerable rpc

Cargo.lock, cli/Cargo.toml, enclave-runtime/Cargo.lock, enclave-runtime/Cargo.toml, enclave-runtime/src/ocall/attestation_ocall.rs, service/Cargo.toml
=> remove EPID call for mrenclave of self

app-libs/parentchain-interface/src/indirect_calls/shield_funds.rs, app-libs/stf/src/trusted_call.rs, cli/demo_shielding_unshielding_multiworker.sh, core-primitives/stf-primitives/src/error.rs, service/src/main_impl.rs
close #1679 
Only sidechain worker mode has a use for a shard vault. skip otherwise
=> skip shard vault creation if teeracle or OCW

app-libs/assets-map/src/lib.rs, app-libs/stf/src/trusted_call.rs
contract address: https://etherscan.io/token/0x1aBaEA1f7C830bD89Acc67eC4af516284b1bC33c
issuer: https://www.circle.com/eurc
=> add EURC.e support
