integritee-network/worker

Cargo.toml
client/Cargo.toml
enclave/Cargo.toml
enclave/balances/Cargo.toml
stf/Cargo.toml
substratee-node-calls/Cargo.toml
worker/Cargo.toml
worker/worker-api/Cargo.toml

* we now depend on scs/substrate@f17d023bbe179f15678ac9989f471c9b18917e17 (upstream commit)
* patched primitives and application_crypto are drawn from scs/substrate@substraTEE-M5.1

move dependencies to scs fork

---

.gitignore
Makefile
README.md
enclave/Cargo.toml
enclave/Enclave.config.production.xml
enclave/src/attestation.rs
enclave/src/constants.rs
worker/Cargo.toml
worker/src/constants.rs
worker/src/enclave/init.rs
worker/src/main.rs

Default make target is still development. Production mode can be enabled with `SGX_PRODUCTION=1 make`

Add support for Intel commercial license

---

enclave/Cargo.toml
enclave/src/aes.rs
enclave/src/attestation.rs
enclave/src/ed25519.rs
enclave/src/io.rs
enclave/src/lib.rs
enclave/src/rsa3072.rs
enclave/src/state.rs
enclave/src/tls_ra.rs
enclave/src/utils.rs
substrate-sgx/externalities/Cargo.toml
substrate-sgx/externalities/src/lib.rs
worker/Cargo.toml

* [enclave]: mostly refactoring `utils` into several modules and gave more meaningful and concise names that take into account the namespacing of the modules
* [enclave] also extracted some methods of the `lib.rs` file into modules
* some general cleanup

Cl cleanup enclave

---

Cargo.lock
enclave/Cargo.lock
enclave/src/lib.rs
stf/src/sgx.rs
worker/src/main.rs
worker/src/tests/integration_tests.rs

* fix execute-stf: problem was ocall_worker request. Storage was trying to be decoded into a `Vec<u8>`, which is not possible. Now use `api.get_opaque_storage_by_keyhash` to get directly the storage as `Vec<u8>`
* re-enable extrinsics by the STF

fix-execute-stf

---

Cargo.lock
client/Cargo.toml
enclave/Cargo.lock
enclave/Cargo.toml
enclave/chain_relay/src/lib.rs
enclave/chain_relay/src/state.rs
enclave/src/lib.rs
substratee-node-calls/Cargo.toml
worker/Cargo.toml
worker/src/main.rs
worker/src/tests/integration_tests.rs
worker/src/tests/mod.rs

* [chain_relay] can now verify inclusion of opaque extrinsics in a submitted block
* [enclave] `execute_stf` now keeps track of the call confirmed extrinsics that have been sent by the enclave. Enclave now refuses to continue working if there are unconfirmed extrinsics.
* [worker] add chain_relay logic to main.
->  demo_private_tx* has been executed successfully

check-call-confirmed-transaction-inclusion

---

Cargo.lock
client/src/main.rs
enclave/Cargo.lock
enclave/src/lib.rs
stf/src/cli.rs
worker/src/cli.yml
worker/src/main.rs
worker/src/ws_server.rs
worker/worker-api/src/lib.rs

+ generic return values for TrustedGetter (still maximum-sized)
! fix init-shard cli to use base58 encoding
! prevent panics causes by TrustedCalls

Brenzi generic trusted operation returns

---

README.md

Name and description of docker image was wrong. Pointing to a non-existant version

README: Fix name of docker image

---

Cargo.lock
enclave/Cargo.lock
enclave/src/lib.rs
stf/Cargo.toml
stf/src/sgx.rs

* check in unshield call if there is enough funds to perform the operation
* Introduce `StfError`
* Return `Result<(), StfError>` in `Stf::execute`
* enclave recovers if `Stf::execute` fails and simply logs an error.

Cl stf unshield check negative balance

---

enclave/src/attestation.rs
stf/Cargo.toml
stf/src/lib.rs
stf/src/sgx.rs
worker/src/enclave/api.rs
worker/src/tests/commons.rs
worker/src/tests/ecalls.rs
worker/src/tests/integration_tests.rs
worker/src/ws_server.rs

**[STF]** 
* check in  `TrustedCall::set_balance` if the signer is root. Alice has been added as root account.
* Fix toml such that cargo test works again
**[Worker]**
* enclave_api: adjust return type of enclave_shielding_key
* ecalls: remove todos for test_get_shielding_key/ test_get_signing_key. They are implicitly tested in all integration tests in more expressive manner.
Closes #23 , the remaining points have been made to separate issues.

Cl fixme todos

---

Cargo.lock
client/Cargo.toml
client/src/main.rs
enclave/src/lib.rs
stf/src/sgx.rs
substratee-node-primitives/Cargo.toml
substratee-node-primitives/src/lib.rs
worker/Cargo.toml
worker/src/main.rs

* bump node: v0.6.6-sub2.0.0-alpha.7
* include hash of trusted_call_signed in shield_funds extrinsic
* change call_hash to H256

mitigate-involuntary-replay-attack-in-unshield

---

Cargo.lock
client/Cargo.toml
enclave/Cargo.lock
enclave/Cargo.toml
enclave/Enclave.edl
enclave/chain_relay/Cargo.toml
enclave/src/cert.rs
enclave/src/tls_ra.rs
stf/Cargo.toml
substratee-node-primitives/Cargo.toml
substratee-node-primitives/src/lib.rs
worker/Cargo.toml
worker/src/cli.yml
worker/src/enclave/tls_ra.rs
worker/src/main.rs
worker/worker-api/Cargo.toml

This pull request fixes the mutual remove attestation, which was broken with to the introduction of shards. The enclave state is no longer provisioned in mutual remote attestation as each enclave can reproduce past worker requests upon block inclusion from the chain relay.
**mutual remote attestation**
* fix mr_enclave check, which possibly never worked
* remove state provisioning as every enclave can now calculate its state from genesis
**worker**
* use `get_first_worker_not_equal_to_self` instead of `get_worker_for_shard` to request key provisioning as no state is exchanged anymore in mura. Closes #146 
* fix cli for provisioning tests, which possibly never worked since the cli revamp long ago.

fix running multiple workers

---

enclave/src/lib.rs
enclave/src/state.rs
stf/src/sgx.rs
worker/src/main.rs

the enclave does now perform a state update on every shard upon block import with the keys given by the newly introduced `STF::storage_hashes_to_update_on_block`
As of now the enclave creates a new shard if it does not exist already.
Every shard located in the `shards` directory is updated.

on block storage updates for every shard

---

Cargo.lock
enclave/Enclave.edl
enclave/src/attestation.rs
enclave/src/lib.rs
enclave/src/state.rs
stf/src/lib.rs
stf/src/sgx.rs
worker/Cargo.toml
worker/src/enclave/api.rs
worker/src/main.rs

**worker**
* use `lazy_static` to get a global static reference to the node_url. With this, we no longer need to pass the url into the enclave.
**enclave/stf**
* perform on-chain storage updates in get_state if needed

allow on chain read in get state

---

client/src/main.rs
enclave/src/lib.rs
enclave/src/state.rs
stf/src/lib.rs
stf/src/sgx.rs
worker/src/main.rs
worker/worker-api/src/lib.rs

[enclave] update_map contains options. This is needed if a storage value needs to be deleted in the STF
[enclave, stf] perform state updates per shard, auto join new shards

automatic-shard-joining-and-per-shard-updates-on-block

---

Cargo.lock
worker/Cargo.toml
worker/src/ipfs.rs

update versions of 
- ipfs_api
- futures
Use tokio for async runtime, like example in ipfs_api

update rust_ipfs_api version

---

Cargo.lock
README.md
client/Cargo.toml
enclave/Cargo.lock
enclave/Cargo.toml
enclave/chain_relay/Cargo.toml
enclave/src/constants.rs
stf/Cargo.toml
stf/src/lib.rs
substratee-node-primitives/Cargo.toml
worker/Cargo.toml
worker/src/main.rs
worker/worker-api/Cargo.toml

Upgrade upstream 2.0.0

---

enclave/Enclave.edl
enclave/src/lib.rs
enclave/src/rpc/author/mod.rs
stf/src/sgx.rs
worker/src/enclave/api.rs
worker/src/main.rs

only commit [1ec6a08](https://github.com/scs/substraTEE-worker/pull/220/commits/1ec6a088dd4aa6a97d5e3bafcb9176763ae75956) is new. The other commits have already been [merged](https://github.com/scs/substraTEE-worker/pull/217) and successfully reviewed.

Return block confirmations with ocall instead of ecall

---

client/src/main.rs
enclave/src/lib.rs
stf/src/lib.rs
worker/src/main.rs

produce one block confirmation per layer one block
(maybe just one block confirmation if an actual indirect call is executed is better?)

Indirect block production

---

client/demo_direct_call.sh
client/demo_private_tx.sh
client/src/main.rs
enclave/src/lib.rs
stf/src/lib.rs
substratee-node-primitives/src/lib.rs
worker/src/main.rs

Reenables indirect invocation, with block confirmation instead of call confirmation
Current Problem that should be fixed in the future: for every individual indirect call the shard state is loaded and written. Very ineffective..
Is that acceptable for now?

Sidechain reenable indirect invocation

---

Makefile

The worker build.rs defaults to `SGX_MODE=HW` if the env var is not set. 
As the env var was not correctly propagated to the build script, SW builds were broken because the enclave was correctly built in SW mode but the worker in HW, which resulted in an `SGX_ERROR_INCOMPATIBLE_MODE` when initializing the enclave.

[Makefile] Fix propagation of SGX_MODE to worker build.

---

client/src/main.rs
enclave/src/cert.rs
enclave/src/ipfs.rs
enclave/src/lib.rs
enclave/src/rpc/worker_api_direct.rs
enclave/src/tests.rs
enclave/src/tls_ra.rs
enclave/src/top_pool/base_pool.rs
enclave/src/top_pool/pool.rs
enclave/src/top_pool/ready.rs
enclave/src/utils.rs
stf/src/cli.rs
worker/rpc/client/src/direct_client.rs
worker/src/tests/mock.rs
worker/src/worker.rs

Make bigna happy by fixing new clippy warnings that occur after clippy update.
Todo:

Fix warning

---

enclave/Cargo.lock
enclave/Cargo.toml
enclave/src/error.rs
enclave/src/lib.rs

Introduce enclave error

---

enclave/Enclave.config.production.xml
enclave/Enclave.config.xml

This increases the amount of trusted threads that can be launched, and should fix the jenkins CI.
I do this now, as I don't exactly know, how long it takes to finish GitHub actions CI.
When jenkins is happy again, we can start merging all the PRs.
Closes: #304

[enclave] increase TCSNUM to 8

---

enclave/src/attestation.rs
enclave/src/lib.rs
enclave/src/ocall/attestation_ocall.rs
enclave/src/ocall/ffi.rs
enclave/src/ocall/mod.rs
enclave/src/ocall/ocall_api.rs
enclave/src/ocall/ocall_component_factory.rs
enclave/src/tls_ra.rs

Draft PR to review a design proposition for an OCall API in the Enclave. The API so far is only done for the remote attestation calls, none of the other o-calls are included in this draft.

Review of OCall API Draft in Enclave

---

enclave/src/lib.rs
enclave/src/tests.rs
local-setup/launch.py
worker/src/error.rs
worker/src/globals/mod.rs
worker/src/globals/tokio_handle.rs
worker/src/globals/worker.rs
worker/src/main.rs
worker/src/node_api_factory.rs
worker/src/ocall_bridge/bridge_api.rs
worker/src/ocall_bridge/component_factory.rs
worker/src/ocall_bridge/ffi/get_ias_socket.rs
worker/src/ocall_bridge/ffi/get_quote.rs
worker/src/ocall_bridge/ffi/get_update_info.rs
worker/src/ocall_bridge/ffi/init_quote.rs
worker/src/ocall_bridge/ffi/mod.rs
worker/src/ocall_bridge/ffi/send_block_and_confirmation.rs
worker/src/ocall_bridge/ffi/worker_request.rs
worker/src/ocall_bridge/remote_attestation_ocall.rs
worker/src/ocall_bridge/worker_on_chain_ocall.rs
worker/src/sync_block_gossiper.rs

This is based on #293 - draft review for now
Refactor the abstractions for the onchain ocalls. This required some additional refactoring of our global variables in the main file (see https://github.com/integritee-network/worker/blob/344b53796636868c96430fbbc6dfdccbc00d3af0/worker/src/main.rs#L91-L96 ). Access to these is now wrapped in separate `Accessor` traits. These can be injected and so the nature of the global variables can be hidden.
This now started building the object dependency tree, that we initialize upon application startup and then distribute to wherever it is needed. Unfortunately, because of the nature of the ocalls (and because we can't pass all of the state into the enclave), we still need that global state outside the enclave.
A diagram of this refactoring:

worker ocall abstraction onchain

---

worker/src/main.rs
worker/src/ocall_bridge/bridge_api.rs
worker/src/ocall_bridge/component_factory.rs
worker/src/ocall_bridge/ffi/ipfs.rs
worker/src/ocall_bridge/ffi/mod.rs
worker/src/ocall_bridge/ipfs_ocall.rs
worker/src/ocall_bridge/mod.rs
worker/src/ocall_bridge/worker_on_chain_ocall.rs

Add the IPFS o-calls to the OCallBridge. Quite a 'small' change set, following the same pattern as we have seen and discussed in #299.
Only a draft PR, since this has to be rebased and retargeted to master, once #299 is merged

Add Ipfs Ocall API and impl to the ocall bridge

---

enclave/src/lib.rs
enclave/src/ocall/ocall_api.rs
enclave/src/ocall/on_chain_ocall.rs
enclave/src/test/on_chain_ocall_tests.rs
primitives/worker/src/lib.rs
worker/src/main.rs
worker/src/ocall_bridge/worker_on_chain_ocall.rs

Allows us to share the definitions, and remove the duplicates in the untrusted worker and enclave
Closes #142

Move WorkerRequest and WorkerResponse to worker primitives

---

.github/workflows/build_and_test.yml
enclave/src/lib.rs
worker/src/tests/ecalls.rs
worker/src/tests/mod.rs

Get state does not sync with layer one chain

---

enclave/Cargo.toml
enclave/Makefile
enclave/src/lib.rs
enclave/src/state.rs
enclave/src/tests.rs
enclave/src/top_pool/base_pool.rs
enclave/src/top_pool/pool.rs
enclave/src/top_pool/primitives.rs
stf/Cargo.toml
stf/src/lib.rs
stf/src/sgx.rs
stf/src/stf_sgx.rs
stf/src/stf_sgx_primitives.rs
stf/src/test_genesis.rs

* STF crate has a new `test_accounts` feature - this will endow the `Alice` and another test account upon initialization
* The enclave has a new `test` feature that activates the `test_accounts` feature in the STF create in case of development mode, and disabled in production mode
* In production mode, the enclave has a dummy implementation for the e-call `test_main_entrance()`
* Also moved the tests to a separate sub-module `tests` in some module in the enclave
Closes #215

Introduce 'test' feature, endow accounts in STF only in test feature

---

enclave/chain_relay/src/lib.rs
enclave/src/io.rs
enclave/src/lib.rs
worker/src/main.rs

I've done a couple of refactorings in the worker code concerning the `produce_blocks` workflow. Mostly extracted methods to shorten and clarify long existing methods. In some places also shared duplicated code.

Minor refactorings after sifting through the 'produce_blocks' code

---

Cargo.lock
Cargo.toml
enclave/Cargo.lock
enclave/Cargo.toml
enclave/src/attestation.rs
enclave/src/cert.rs
enclave/src/lib.rs
enclave/src/ocall/attestation_ocall.rs
enclave/src/ocall/ipfs_ocall.rs
enclave/src/ocall/mod.rs
enclave/src/ocall/ocall_component_factory.rs
enclave/src/ocall/on_chain_ocall.rs
enclave/src/ocall/rpc_ocall.rs
enclave/src/onchain/storage.rs
enclave/src/rpc/basic_pool.rs
enclave/src/test/ipfs_tests.rs
enclave/src/test/mocks/attestation_ocall_mock.rs
enclave/src/test/mocks/enclave_rpc_ocall_mock.rs
enclave/src/test/on_chain_ocall_tests.rs
enclave/src/tests.rs
enclave/src/tls_ra.rs
enclave/src/top_pool/listener.rs
enclave/src/top_pool/pool.rs
enclave/src/top_pool/validated_pool.rs
enclave/src/top_pool/watcher.rs
primitives/ocall-api/Cargo.toml
primitives/ocall-api/src/lib.rs

I just realized, that with `ocall_api` abstractions, it is only the innermost implementation of the ocalls that need the sgx stuff. If we make the `ocall_api` available as separate crate, we can independently use it and start using cargo test in dependants.

[enclave/sidechain] move ocall_api to its own crate.

---

Cargo.lock
enclave/Cargo.lock
enclave/Cargo.toml
enclave/src/rpc/worker_api_direct.rs
primitives/worker/Cargo.toml
primitives/worker/src/lib.rs
primitives/worker/src/rpc.rs

The worker primitives crate has now all its module available in the SGX environment (specifically the RPC structs that use serde)

Worker primitives are made SGX compatible, with all modules (including rpc)

---

enclave/chain_relay/Cargo.toml
enclave/chain_relay/src/error.rs
enclave/chain_relay/src/justification.rs
enclave/chain_relay/src/lib.rs

- removal of communication block (speficially functions `localized_payload_with_buffer` and `check_message_sig_with_buffer`) because they are now implemented in the [sp_finality_grandpa crate](https://github.com/paritytech/substrate/tree/master/primitives/finality-grandpa) which implements no_std.
- adaptions (mostly copy paste) according to substrate [sc-finality-grandpa justifications.rs](https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/src/justification.rs)
- chain relay will not panic upon faulty justification but print an error message

[chain relay] update justifications

---

local-setup/py/worker.py

Before we got state inconsistencies with the local setup as only the shards were purged, but not the sidechain db. 
Before this fix, a restart of the local setup resulted in some invalid block ancestry errors.

[local-setup] change shard purging logic for new sidechain_db

---

Cargo.lock
app-libs/stf/src/stf_sgx.rs
core-primitives/ocall-api/Cargo.toml
core-primitives/ocall-api/src/lib.rs
core-primitives/types/src/lib.rs
enclave-runtime/Cargo.lock
enclave-runtime/src/lib.rs
enclave-runtime/src/ocall/on_chain_ocall.rs
enclave-runtime/src/tests.rs
service/src/ocall_bridge/worker_on_chain_ocall.rs

Minor adjustment I did while preparing aura.

move `OpaqueCall` to itp_types and use `OpaqueExtrinsic` consistently

---

core-primitives/enclave-api/ffi/src/lib.rs
core-primitives/enclave-api/src/side_chain.rs
enclave-runtime/Enclave.edl
enclave-runtime/src/lib.rs
service/src/main.rs
service/src/tests/integration_tests.rs

In was intended that we produce sidechain blocks at a certain interval. However, this did actually not work as it should before.
The implementation before failed to call in the enclave if there were no `blocks_to_sync`. Hence, the sidechain's block production time was limited to the parentchain's block production time.
This is fixed here, we call into the enclave regardless of `blocks_to_sync` being empty or not.
Closes #405

Fix interval block production

---

Cargo.lock
Cargo.toml
core/rest-client/Cargo.toml
core/rest-client/src/error.rs
core/rest-client/src/http_client.rs
core/rest-client/src/http_client_builder.rs
core/rest-client/src/lib.rs
core/rest-client/src/mocks/http_client_mock.rs
core/rest-client/src/mocks/mod.rs
core/rest-client/src/rest_client.rs

As discussed in #390 
- New crate for a REST client (`/core/rest-client/`) that allows secure connections (TLS, based on `rustls`)
- Uses the [http_req](https://github.com/jayjamesjay/http_req) and its corresponding SGX port for the HTTP(S) requests
- REST client is heavily inspired by (i.e. copied and modified from) [restson](https://github.com/spietika/restson-rust). This client however is based on `hyper` to do the HTTP requests, which is not available as a SGX port.
- All requests are done in a blocking fashion, no `async/await` since `http_req` is blocking (unlike `hyper`)
Closes #390

New REST client crate, based on http_req and rustls

---

Makefile
enclave-runtime/Makefile

Use `cargo --release` also in case of `SGX_DEBUG=1` and hence also the corresponding `target/release` folder. 
This still might not be the best debugging experience - but that would be a lot tougher to achieve (if not impossible), considering the nature of the enclave (which cannot be debugged by design).
Closes #375

Fix build for SGX_DEBUG=1

---

enclave-runtime/src/lib.rs
enclave-runtime/src/rpc/author/mod.rs

I refactored the RPC author API so we only have this one facade to do all the operations, instead of having a mixture of author and top pool directly. This will allow us to pass in only the author and hide the top pool for most of the functions.

Refactor RPC author as facade

---

enclave-runtime/src/lib.rs
enclave-runtime/src/rpc/author/mod.rs
enclave-runtime/src/rpc/worker_api_direct.rs
enclave-runtime/src/tests.rs
enclave-runtime/src/top_pool/error.rs

The RPC author is now responsible for locking and unwrapping the top pool it uses. Now owns a top pool getter and does not have to be constructed on the fly. 
This is done in preparation for the `Author` to have a filter feature and use an internal member to access the Rsa3072 shielding key, rather than using static/global access (which is a 'hidden' dependency and very difficult to test)

RPC Author encapsulates top pool and mutex access

---

Cargo.lock
app-libs/stf/Cargo.toml
app-libs/stf/src/stf_sgx.rs
core-primitives/ocall-api/Cargo.toml
core-primitives/ocall-api/src/lib.rs
core-primitives/types/Cargo.toml
core-primitives/types/src/lib.rs
core/light-client/src/io.rs
core/light-client/src/lib.rs
core/light-client/src/state.rs
core/rpc-server/Cargo.toml
core/rpc-server/src/lib.rs
core/rpc-server/src/mock.rs
enclave-runtime/Cargo.lock
enclave-runtime/src/rpc/basic_pool.rs
enclave-runtime/src/rpc/worker_api_direct.rs
enclave-runtime/src/tests.rs
service/Cargo.toml
service/src/main.rs
service/src/ocall_bridge/component_factory.rs
service/src/ocall_bridge/worker_on_chain_ocall.rs
service/src/sidechain_storage/interface.rs
service/src/sidechain_storage/mod.rs
service/src/sidechain_storage/storage.rs
service/src/sync_block_gossiper.rs
service/src/tests/commons.rs
service/src/worker.rs
sidechain/primitives/src/types/mod.rs

I needed some type from `itp_type` in `its-primitives` in aura, which resulted in cyclic dependencies. In the end, I removed that again, so this PR would not be strictly necessary. :)
However, I think we should have these two crates clearly separated.

[itp-types] remove re-export of sidechain-primitives in itp-types

---

Makefile
sidechain/consensus/aura/src/lib.rs
sidechain/consensus/slots/src/lib.rs
sidechain/consensus/slots/src/slots.rs

This fixes a potential divide by zero panic, which could only occur in a corner-case.
Closes #439

Fix potential panic in slot derivation.

---

enclave-runtime/src/lib.rs
enclave-runtime/src/rpc/author/author_container.rs
enclave-runtime/src/rpc/author/author_tests.rs
enclave-runtime/src/rpc/author/client_error.rs
enclave-runtime/src/rpc/author/mod.rs
enclave-runtime/src/rpc/author/test_utils.rs
enclave-runtime/src/rpc/author/top_filter.rs
enclave-runtime/src/tests.rs
enclave-runtime/src/top_pool/validated_pool.rs

The RPC author now takes a filter for the trusted operations, which allows to disable certain trusted operations, like trusted calls (to only allow trusted getters).
- by default, all tops are allowed in the author
- if an operation is received that is filtered out, an error is
returned
Closes #415 #416

Add new filter feature for trusted operations in the RPC author

---

core-primitives/enclave-api/ffi/src/lib.rs
core-primitives/enclave-api/src/side_chain.rs
enclave-runtime/Enclave.edl
enclave-runtime/src/lib.rs
service/src/error.rs
service/src/main.rs
service/src/tests/integration_tests.rs

Up until now syncing the parent chain and executing trusted operations was done in the same loop. We now separate the two tasks and run them in separate threads. The parent chain syncing is triggered by subscribing to the new header event in the node API. The TOP execution is kept in the same 300ms time slot loop.
Closes #404

Separate parentchain sync from top execution

---

.github/workflows/build_and_test.yml
cli/demo_direct_call.sh
cli/demo_shielding_unshielding.sh
core-primitives/settings/src/lib.rs
enclave-runtime/src/lib.rs

- update spec-version from 2 -> 3
- change indirect block confirmation that used genesis hash as shard to mrenclave. This is necessary becasue pallet teerex throws an error otherwise: https://github.com/integritee-network/pallets/blob/master/teerex/src/lib.rs#L202
Temporary fix only. Will be cleaned up with issue https://github.com/integritee-network/worker/issues/457
closes #475

Update to new node: indirect block confirm: genesis hash -> mrenclave

---

Cargo.lock
Cargo.toml
core-primitives/types/src/rpc.rs
enclave-runtime/Cargo.lock
enclave-runtime/src/lib.rs
enclave-runtime/src/rpc/worker_api_direct.rs
enclave-runtime/src/sidechain_impl.rs
enclave-runtime/src/tests.rs
sidechain/rpc-handler/Cargo.toml
sidechain/rpc-handler/src/direct_top_pool_api.rs
sidechain/rpc-handler/src/import_block_api.rs
sidechain/rpc-handler/src/lib.rs
sidechain/sidechain-crate/Cargo.toml
sidechain/sidechain-crate/src/lib.rs
sidechain/top-pool-rpc-author/src/author_container.rs
sidechain/top-pool-rpc-author/src/global_author_container.rs
sidechain/top-pool-rpc-author/src/initializer.rs
sidechain/top-pool-rpc-author/src/pool_types.rs
sidechain/top-pool-rpc-author/src/traits.rs

The new crate is 'top-pool-rpc' in the 'sidechain' folder. Extracted code from `worker_api_direct.rs` in the `enclave_runtime`.
This is a further step towards moving sidechain features out of the `enclave-runtime`.

Extract the top pool direct invocation RPC interface to a separate crate

---

Cargo.lock
core/rest-client/Cargo.toml
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml

We have our own forks of http and httparse (for now). With this change we make sure that we use those consistently.

Use the same version of http and httparse in the enclave dependencies

---

core-primitives/stf-executor/Cargo.toml
core-primitives/stf-executor/src/executor.rs
enclave-runtime/src/cert.rs
sidechain/consensus/slots/Cargo.toml
sidechain/consensus/slots/src/slots.rs
sidechain/top-pool/Cargo.toml
sidechain/top-pool/src/future.rs
sidechain/top-pool/src/pool.rs
sidechain/top-pool/src/validated_pool.rs

This renders the `use std::untrusted::time::*` imports obsolete.
We do this because in a feature branch we encountered clippy issues about these imports being unused (in #442 ). It is still not entirely clear why these clippy warnings appear on that specific branch.
One suspicion is, that somehow a new/changed dependency now enables the `sgx_tstd/untrusted_time` feature which wasn't the case before.

Specify 'untrusted_time' feature explicitely in crates with sgx_tstd

---

enclave-runtime/src/lib.rs
enclave-runtime/src/sidechain_block_composer.rs
enclave-runtime/src/sidechain_impl.rs
enclave-runtime/src/sync.rs
enclave-runtime/src/tests.rs
enclave-runtime/src/top_pool_execution.rs
enclave-runtime/src/top_pool_operation_executor.rs
enclave-runtime/src/utils.rs
sidechain/consensus/common/src/block_import.rs
sidechain/top-pool-rpc-author/src/author_tests.rs
sidechain/top-pool-rpc-author/src/test_utils.rs

Created new traits/components that execute the trusted operations from the top pool.
Also separated the execution and block/confirmation composition.
The is in preparation for moving these parts into the sidechain crate.

Extract the top pool operation execution into separate modules

---

cli/demo_direct_call.sh
cli/demo_shielding_unshielding.sh
cli/src/main.rs

Fix event decoding in cli + remove timeout in demos

---

enclave-runtime/Cargo.toml

Removes feature imports from patches as they are ignored by the compiler and are thus misleading. (And the compiler warns about them, which is not a good sign)

[enclave-runtime] remove misleading feature imports from patches

---

.github/workflows/build_and_test.yml
Cargo.lock
Cargo.toml
app-libs/exchange-oracle/Cargo.toml
app-libs/exchange-oracle/src/coingecko.rs
app-libs/exchange-oracle/src/error.rs
app-libs/exchange-oracle/src/lib.rs
core-primitives/api-client-extensions/src/lib.rs
core-primitives/api-client-extensions/src/pallet_teeracle.rs
core-primitives/enclave-api/ffi/src/lib.rs
core-primitives/enclave-api/src/lib.rs
core-primitives/enclave-api/src/teeracle_api.rs
core-primitives/settings/src/lib.rs
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml
enclave-runtime/Enclave.edl
enclave-runtime/src/lib.rs
service/Cargo.toml
service/src/main.rs

DO NOT MERGE THIS INTO MASTER
it's a showcase that may reside on a branch for now

Add exchange-oracle crate and implement get_exchange_rate for coinGecko

---

Cargo.lock
core/light-client/Cargo.toml
core/light-client/src/concurrent_access.rs
core/light-client/src/error.rs
core/light-client/src/lib.rs
core/light-client/src/mocks/mod.rs
core/light-client/src/mocks/validator_mock.rs
core/light-client/src/mocks/validator_mock_seal.rs
enclave-runtime/Cargo.lock
enclave-runtime/src/lib.rs
enclave-runtime/src/sync.rs
enclave-runtime/src/top_pool_execution.rs

Before we acquired a (write) lock for an entire e-call, and it had to be done explicitly and thus could be forgotten. Now we acquire the lock implicitly when we read or write from/to the light client and on a per-operation basis.
This is a preparation for #423, where we will need to modify the block import behavior and need granular locking to prevent deadlocks.

Refactor locking mechanism of light client to ensure granular exclusive access

---

.github/workflows/build_and_test.yml

This should fix some CI failures we see after we increased the block production time in the node from 6s to 12s
(see https://github.com/integritee-network/integritee-node/commit/ada0c26a133e82787ff4a2028ae7f8fcb3d08510)

Increase sleep time for local setup after increase of block production time

---

enclave-runtime/src/attestation.rs
enclave-runtime/src/cert.rs
enclave-runtime/src/tls_ra.rs
enclave-runtime/src/utils.rs

Removed the trait UnwrapOrSgxErrorUnexpected replaced
- sgx_error by map_err(|_| sgx_status_t::SGX_ERROR_UNEXPECTED) or ok_or(sgx_status_t::SGX_ERROR_UNEXPECTED)
- sgx_error_with_log by .map_err(|e| {error!("    [Enclave] failed to create TcpStream: {:?}", e);sgx_status_t::SGX_ERROR_UNEXPECTED})?;
Closes #413

Remove trait UnwrapOrSgxErrorUnexpected

---

.github/workflows/build_and_test.yml
Cargo.lock
Cargo.toml
app-libs/stf/src/stf_sgx.rs
app-libs/stf/src/test_genesis.rs
cli/Cargo.toml
cli/src/main.rs
core/parentchain/indirect-calls-executor/src/indirect_calls_executor.rs
core/parentchain/light-client/src/lib.rs
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml
service/Cargo.toml
service/src/main.rs
service/src/tests/integration_tests.rs
sidechain/top-pool/src/pool.rs

For compatibility reason, the node requiring V14 metadata https://github.com/integritee-network/integritee-node/issues/83

Upgrade substrate to  7406442bea0194ffcafc4e8d48d895d4d8d11346 

---

Cargo.lock
service/Cargo.toml
service/src/main.rs
sidechain/consensus/slots/Cargo.toml
sidechain/consensus/slots/src/lib.rs
sidechain/consensus/slots/src/slot_stream.rs

When a trusted call takes longer than the slot duration the wait time until the next slot is adapted to avoid drifts.
Closes #504

[sidechain] loop function without drift. 

---

.github/workflows/build_and_test.yml

This was introduced for PR #541 to have a valid CI build when merging into #520. Now it has to be removed again.

Remove obsolete branch from pull-request target builds

---

Cargo.lock
core/rpc-server/Cargo.toml
core/rpc-server/src/mock.rs
core/rpc-server/src/tests.rs
service/Cargo.toml
service/src/tests/commons.rs
service/src/worker.rs
sidechain/consensus/aura/Cargo.toml
sidechain/consensus/aura/src/block_importer_tests.rs
sidechain/consensus/aura/src/lib.rs
sidechain/consensus/aura/src/mock.rs
sidechain/consensus/aura/src/verifier.rs
sidechain/test/Cargo.toml
sidechain/test/src/lib.rs
sidechain/test/src/sidechain_block_builder.rs

Move TestBlockBuilder to its own crate & rename to SidechainBlockBuilder, as it's not aura specific.
I'm unsure if the test crate is correct place for that, I'm open for your opinion here.
I did not want to place it in the itp-test crate, as it's sidechain specific.
@gaudenzkessler @echevrier please give your review as well. Most important would be : Would you find the `SidechainBlockBuilder `again, in case you'd need to for a test? And if not, where would you expect it?

Move sidechain block builder to separate crate

---

.github/workflows/build_and_test.yml
core/rest-client/src/http_client.rs
core/rest-client/src/lib.rs

Add tests to ensure that per default the http client blocks the connection for some certificates known to be insecure, as https://github.com/integritee-network/worker/issues/552 cannot be implemented for now:
Check following certificates: 
- Self signed certificate
- let's encrypt certificates from test set-up. See https://letsencrypt.org/certificates/

Test https connection with different certificates which should be blocked

---

.github/workflows/build_and_test.yml
core-primitives/settings/src/lib.rs

@gaudenzkessler this will make the worker compatible with the newest integritee-node docker container.

Bump integritee-node runtime spec

---

cli/src/main.rs
core-primitives/api-client-extensions/src/pallet_teerex.rs
enclave-runtime/src/lib.rs
service/src/error.rs
service/src/main.rs
service/src/parentchain_block_syncer.rs
service/src/tests/mock.rs
service/src/tests/parentchain_block_syncer_test.rs
service/src/tests/worker.rs
service/src/worker.rs

solves #589 
- Introduces a little more flexibility to PalletTeerexApi functions with the introduction of `block_at` variable.
- if we're the first validateer to register, we sync all parentchain blocks up until the one we have registered ourselves in.

bootstrap parentchain blocks for primary validateer

---

service/src/globals/tokio_handle.rs
service/src/worker.rs

This is cherry picked from a future PR of mine. Should resolve #570 .
When we instantiate the tokio runtime, we limit the number of worker threads to 2 for now, to avoid running out of enclave TCS (as is the case in #570). 
When the tokio runtime is default constructed, it will use as many worker threads as cores are available. So as soon as we put some load onto the tokio tasks, we saturate the threads and more. And since the gossiping calls into the enclave, we use a TCS for every worker thread.

Tokio runtime limited to 2 worker threads, gossiping leverages async tasks

---

local-setup/tutorial-config.json

The sidechain tutorial uses the local setup to run an integritee node and 2 workers. For that it needs an appropriate config file.

Add a local-setup config to the tutorial (integritee book)

---

service/src/alive_service.rs
service/src/initialized_service.rs
service/src/main.rs

* Introduced an http service which returns 200 (OK) if the service is not fully up and 404 (not found), if  not
* set this alive value to true, at the end of start worker method
* ![image](https://user-images.githubusercontent.com/92718752/160805542-7cbd938c-e37d-4549-8719-6de6f04be7b5.png)
closes #695

create alive service to deterine that the service is up, running and registered

---

scripts/init_env.sh

Bash scripts should have an `set -e` statement to prevent the script to continue in case of an error. In an environment file that is importet via `source` you should not have this statement, since this behaviour is overtaken to the current session. 
It is save to delete the statement from `init_env.sh` since there process that can return a result different than 0.

remove set -e from init_env.sh source

---

README.md
cli/src/trusted_operation.rs
core/direct-rpc-server/src/lib.rs
core/direct-rpc-server/src/rpc_connection_registry.rs
core/rpc-client/src/direct_client.rs
core/tls-websocket-server/src/connection.rs
core/tls-websocket-server/src/lib.rs
core/tls-websocket-server/src/test/fixtures/test_server.rs
core/tls-websocket-server/src/test/mocks/web_socket_handler_mock.rs
core/tls-websocket-server/src/ws_server.rs

As reported in #752 and the benchmarking done by @Niederb, the web-socket server could get stuck in an endless loop under certain conditions. This has been fixed in this PR, and also extended the unit tests to cover that case.
* A deadlock between two threads was responsible for the freezing. The web-socket thread and top-pool executor thread both held locks on the top pool and web-socket connections. This is solved by removing the need for a connection lock when sending an RPC response. The action of sending a response is now added to the main event loop of the web-socket server.
Closes #752 #751

Solve potential endless loop in WS server

---

sidechain/consensus/slots/src/slots.rs

We seem to have a flaky unit test now, with the timing of slots. E.g. [here](https://github.com/integritee-network/worker/actions/runs/2453556246) the build on master failed.
Relax the threshold to hopefully reduce the flakiness of the test.

Relax threshold for timing unit test

---

core-primitives/extrinsics-factory/src/lib.rs
core-primitives/extrinsics-factory/src/mock.rs
core/parentchain/block-importer/src/block_importer.rs
enclave-runtime/src/top_pool_execution.rs

Add Option<ParentchainExtrinsicParamsBuilder> parm to create_extrinsics
Default native token.

Fix issue#794: Make the kind of tip we use configurable per set of extrinsics

---

core-primitives/ocall-api/src/lib.rs
core-primitives/test/src/mock/onchain_mock.rs
core-primitives/test/src/mock/sidechain_ocall_api_mock.rs
core/rpc-server/src/mock.rs
enclave-runtime/Enclave.edl
enclave-runtime/src/ocall/ffi.rs
enclave-runtime/src/ocall/sidechain_ocall.rs
enclave-runtime/src/test/mocks/propose_to_import_call_mock.rs
service/src/ocall_bridge/bridge_api.rs
service/src/ocall_bridge/ffi/fetch_sidechain_blocks_from_peer.rs
service/src/ocall_bridge/sidechain_ocall.rs
service/src/ocall_bridge/test/mocks/sidechain_bridge_mock.rs
sidechain/consensus/common/src/block_import.rs
sidechain/consensus/common/src/peer_block_sync.rs
sidechain/peer-fetch/src/block_fetch_client.rs
sidechain/peer-fetch/src/block_fetch_server.rs
sidechain/peer-fetch/src/lib.rs
sidechain/peer-fetch/src/mocks/fetch_blocks_from_peer_mock.rs
sidechain/storage/src/fetch_blocks_mock.rs
sidechain/storage/src/interface.rs
sidechain/storage/src/lib.rs
sidechain/storage/src/storage.rs
sidechain/storage/src/storage_tests_get_blocks_in_range.rs

Before, we peer fetched all blocks that were available on the peer, leading to overlap with the block import queue of a worker. This had to be detected with an 'AlreadyImported' warning.
Because this is inefficient and causes a lot of potentially misleading warnings, this PR changes the mechanism of peer fetching to fetch only the missing blocks.
Closes #821

Peer fetch only missing blocks, not every block available

---

service/src/ocall_bridge/worker_on_chain_ocall.rs

create_api() is a very expensive call as it indirectly spawns three threads.
In my benchmark this change reduces the number of calls per block from 8 to 6.

Move the expensive create_api() call inside the if

---

core-primitives/settings/src/lib.rs
core-primitives/stf-state-handler/src/file_io.rs
service/src/account_funding.rs

- Main change is to increase the initial funding for the enclave.
- Before the enclave would run out of funds after 4 hours, now it is enough for around 80 hours
- Only affects '--dev' mode
- Some minor additions in the logs

800 long running benchmark tests

---

app-libs/stf/src/stf_sgx.rs
app-libs/stf/src/test_genesis.rs

Before adding the new evm pallet I'd like to have this one fixed: closes #535

Add sgx-runtime error feedback to error messages

---

Cargo.lock
core/parentchain/block-importer/Cargo.toml
core/parentchain/block-importer/src/block_importer.rs
core/parentchain/light-client/src/concurrent_access.rs
core/parentchain/light-client/src/mocks/validator_access_mock.rs
enclave-runtime/Cargo.lock
enclave-runtime/src/global_components.rs
enclave-runtime/src/top_pool_execution.rs

We've done some refactorings in the past, that rendered the `OCallApi` type parameter on the `ValidatorAccess` trait obsolete. This PR removes it now.
(this is a small cleanup discovered while doing a proof-of-concept for #836 )

Minor cleanup in light-client: Remove obsolete type parameter

---

Cargo.lock
core-primitives/extrinsics-factory/Cargo.toml
core-primitives/nonce-cache/Cargo.toml
core-primitives/primitives-cache/Cargo.toml
core-primitives/sgx/crypto/Cargo.toml
core-primitives/stf-state-handler/Cargo.toml
core-primitives/test/Cargo.toml
core-primitives/top-pool-author/Cargo.toml
core-primitives/top-pool/Cargo.toml
core/direct-rpc-server/Cargo.toml
core/direct-rpc-server/src/lib.rs
core/parentchain/light-client/Cargo.toml
core/rest-client/Cargo.toml
core/rpc-server/Cargo.toml
core/tls-websocket-server/Cargo.toml
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml
sidechain/consensus/aura/Cargo.toml
sidechain/consensus/common/Cargo.toml
sidechain/consensus/slots/Cargo.toml
sidechain/peer-fetch/Cargo.toml
sidechain/rpc-handler/Cargo.toml
sidechain/state/Cargo.toml

- updates `jsonrpc_core-sgx` to v18
- updates `log-sgx` to v0.4.17
- updates `env_logger-sgx` to v0.9.0
- Some clean up of the Cargo.toml
Error logs are now printed within the enclave again, with full colour and timestamp:
closes #825 
closes #823

Fix message logging within the enclave

---

core/rpc-client/src/direct_client.rs
core/rpc-client/src/ws_client.rs

Currently there is a sender instance remaining on the caller location. This prevents recv() to return as there is still a Sender alive.
- Moving `port_in` into the function instead of passing a reference solves the problem as `port_in` gets dropped inside the function, then `recv()` ends.
- This causes an unnecessary copy but I think it is worth the price
- Explicitly calling `drop(port_in)` on the caller site would also work, but I think it makes sense to change the API in order to prevent these kinds of issues more generally.

Convert Sender to a move parameter

---

docker/docker-compose.yml

so that multiple running instances don't interfere with each other

Docker: remove port mapping

---

Makefile
build.Dockerfile

Update Makefile to run `cargo build` on root level, instead of `cd`-ing into the `service` and `cli` folders and running `cargo build` there.
Also run `cargo test` with `--release` to leverage the dependencies built by the previous steps.

Makefile improvements to speedup CI build

---

service/src/main.rs

the worker printed debug information, that's written into the mrenclave file. Logging has to be done with info! to prevent that.

bugfix mrenclave println problem

---

.github/workflows/build_and_test.yml
build.Dockerfile
core/rpc-client/src/direct_client.rs
core/rpc-client/src/ws_client.rs
docker/README.md
docker/benchmark.yml
docker/demo-direct-call.yml
docker/demo-indirect-invocation.yml
docker/demo-sidechain.yml
docker/docker-compose.yml
docker/fork-inducer.yml
service/src/enclave/mod.rs
service/src/main.rs

Change CI integration tests to using docker images and a docker-compose setup. 
This makes the local python setup obsolete.
Closes #860

Github actions integration tests use docker image instead of python local setup

---

core-primitives/top-pool/src/validated_pool.rs
core/direct-rpc-server/src/rpc_responder.rs
sidechain/top-pool-executor/src/getter_operator.rs

fixes #481 by removing the secondary, unwanted `Invalid` OperationStatus response for a getter query.
Previous Getter responses:
First response:
`[2022-08-25T08:29:53Z DEBUG integritee_cli::trusted_operation] successfully decoded rpc response: RpcReturnValue { value: [1, 64, 152, 146, 152, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], do_watch: false, status: TrustedOperationStatus(Submitted) }`
Second response:
`[2022-08-25T08:29:53Z DEBUG integritee_cli::trusted_operation] successfully decoded rpc response: RpcReturnValue { value: [1, 64, 152, 146, 152, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], do_watch: false, status: TrustedOperationStatus(Invalid) }`
Often perceived Error on the cli side:
``` 
* Send 25000000000 funds from Alice's incognito account to Bob's incognito account
send trusted …
```

Remove needless `Invalid OperationStatus` response for Getter queries

---

app-libs/stf/src/helpers.rs
app-libs/stf/src/lib.rs
app-libs/stf/src/stf_sgx.rs
app-libs/stf/src/stf_sgx_tests.rs
app-libs/stf/src/test_genesis.rs
enclave-runtime/src/test/evm_pallet_tests.rs
enclave-runtime/src/test/sidechain_aura_tests.rs
enclave-runtime/src/test/tests_main.rs

During my work with the Events, I noticed that we can access the pallet getters and their functions directly. This makes the use of many helper functions obsolete. 
Future steps: Let's not return an `Option` for `get_state`. This should now not necessary any more as well.
Changes:
- Access pallet functions directly: 
for example, nonce access of accounts via substrate pallet frame (https://github.com/paritytech/substrate/blob/324a18e3c5cbf333672c54f9367f530ea976928d/frame/system/src/lib.rs#L1488-L1496)):
```rust 
System::inc_account_nonce(&sender);
```
instead of helper function
```rust
/// increment nonce after a successful call execution
pub fn increment_nonce(account: &AccountId) {
//FIXME: Proper error handling - should be taken into
// consideration after implementing pay fee check …
```

Access pallets directly and clean up helper functions

---

Makefile
cli/Cargo.toml
cli/src/commands.rs
cli/src/exchange_oracle/commands/add_to_whitelist.rs
cli/src/exchange_oracle/commands/listen_to_exchange.rs
cli/src/exchange_oracle/commands/mod.rs
cli/src/exchange_oracle/mod.rs
cli/src/main.rs
service/src/main.rs

- updates cli (teeracle-cli is now excluded in non-teeracle compile features)
- updates `print_events` in main.rs with additional compile features
Discovered while doing rebase for Ajuna. Ajuna node runtime does not include pallet_teeracle ( https://github.com/integritee-network/worker/blob/ef5cce1aa12c7ec169b0b64cde19331534afb066/cli/src/exchange_oracle/commands/listen_to_exchange.rs#L48). 
This should not be enforced.
Follow up issue: #981

Do not enforce teeracle and sidechain pallet inclusion in node-runtime

---

.github/workflows/check_labels.yml
.github/workflows/label-checker.yml

The original action failed if the PR came from a fork, which is why it needed some enhancements.*
Some notes:
- The reason it uses `jq` instead of native GitHub Actions features is because a reusable workflow can only accept variables if their type is [one of: `boolean`, `number`, or `string`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype) and there is no builtin `hasSome()` function (unfortunately `contains()` can not look for multiple possbile values).
- Currently if PR has multiple labels from the same type (e.g, `A0` and `A1`) it will pass the check. If it should be limited to exactly one, then let me know and I'll patch it.
*: If somebody could submit a PR (a dummy commit is sufficient enough):
-  to my fork …

GitHub Actions: CI label checker enhancement

---

core-primitives/substrate-sgx/externalities/src/lib.rs
core-primitives/substrate-sgx/sp-io/src/lib.rs

This PR tries to add a basic implementation of `next_key` in SGX sp-io which would have caused problems when doing iterator-based queries. Also see https://github.com/litentry/tee-worker/issues/84
In my (integration) tests with sgx runtime, `iter_values` and `iter_prefix` both work now.
As it's read-only I believe no change to `state_diff` is needed.
It's my first PR so please let me know if anything is inappropriate, thanks!

Implement `next_key` in SGX `sp-io`

---

.github/workflows/check_labels.yml

Label E3 now marks hard to merge PRs instead of a general breaking dependencies. 
General idea:
E5+ labels are breaking changes, everything below marks something that does not break an interface.
Linked issue: #961

Rename label `E3-dependencies` to `E3-hardmerge`

---

Cargo.lock
core-primitives/stf-state-handler/Cargo.toml
core-primitives/stf-state-handler/src/file_io.rs
core-primitives/stf-state-handler/src/state_snapshot_repository.rs
core-primitives/stf-state-handler/src/test/sgx_tests.rs
core-primitives/test/src/mock/handle_state_mock.rs
enclave-runtime/Cargo.lock
enclave-runtime/src/global_components.rs
enclave-runtime/src/initialization.rs
enclave-runtime/src/test/tests_main.rs
enclave-runtime/src/tls_ra/mod.rs
enclave-runtime/src/tls_ra/seal_handler.rs
enclave-runtime/src/tls_ra/tests.rs
enclave-runtime/src/tls_ra/tls_ra_client.rs
enclave-runtime/src/tls_ra/tls_ra_server.rs
service/src/main.rs

Discovered while working on #459 and PR #1077: 
- State and key provisioning failed consistently with state sizes ~25 KB
- Stream reading in provisioning showed weird effects
The issue was, that we read bytes from the TLS stream, but did not check how many bytes we actually read. We provided a buffer with a given size and assumed that `read()` would always fill the buffer. But that is not the case (as the API documentation clearly states). `read()` reads `n` bytes, where `0 <= n <= buffer_size` bytes. So e.g. when we expect to read `1000` bytes (and pre-allocate our buffer accordingly), we must always check how many bytes `read()` actually read, and then call it again, until our buffer is full.
- `initialize_shard` of the `StateSnapshotRepository` will now re-initialize a shard state, …

Fix state provisioning bug when reading large byte buffers

---

cli/demo_direct_call.sh
cli/demo_sidechain.sh
core-primitives/stf-executor/src/executor.rs
docker/docker-compose.yml
enclave-runtime/src/top_pool_execution.rs
sidechain/consensus/aura/src/lib.rs
sidechain/consensus/aura/src/slot_proposer.rs
sidechain/consensus/slots/Cargo.toml
sidechain/consensus/slots/src/lib.rs
sidechain/consensus/slots/src/slots.rs
sidechain/rpc-handler/src/import_block_api.rs
sidechain/test/Cargo.toml

This issue is to investigate the intermittent failures we see in our integration tests.
Related GH issue: #1023 
* Getters in the integration test scripts return wrong results
* We have nonce clashes on rare occasions
* Slot times in about 5% of the cases are exceeded, with 2 effects:
* The proposed block is discarded before it's broadcasted, or
* the block is broadcasted and reaches the import queue AFTER the next block is being produced. This will result in a 'block is already imported' warning.
* Both of the above effects are NOT forks, and will maintain sidechain integrity. What we lose is efficiency and responsiveness.
* Calls from the integration test scripts are executed simultaneously
* I found that we removed the `sleep`s in our integration tests scripts at some point. Those …

Investigate and fix sidechain integration test failures

---

Cargo.lock
app-libs/stf/Cargo.toml
core-primitives/hashing/Cargo.toml
core-primitives/hashing/src/lib.rs
core-primitives/hashing/src/std_hash.rs
core-primitives/settings/src/lib.rs
core-primitives/stf-state-handler/Cargo.toml
core-primitives/stf-state-handler/src/file_io.rs
core-primitives/stf-state-handler/src/in_memory_state_file_io.rs
core-primitives/stf-state-handler/src/lib.rs
core-primitives/stf-state-handler/src/state_handler.rs
core-primitives/stf-state-handler/src/state_initializer.rs
core-primitives/stf-state-handler/src/state_snapshot_primitives.rs
core-primitives/stf-state-handler/src/state_snapshot_repository.rs
core-primitives/stf-state-handler/src/state_snapshot_repository_loader.rs
core-primitives/stf-state-handler/src/test/mocks/initialize_state_mock.rs
core-primitives/stf-state-handler/src/test/mocks/versioned_state_access_mock.rs
core-primitives/stf-state-handler/src/test/sgx_tests.rs
core-primitives/substrate-sgx/externalities/Cargo.toml
docker/docker-compose.yml
enclave-runtime/Cargo.lock
enclave-runtime/src/global_components.rs
enclave-runtime/src/initialization.rs
enclave-runtime/src/ocall/sidechain_ocall.rs
service/src/ocall_bridge/ffi/store_sidechain_blocks.rs

Part of #459 
Worker state is now kept in-memory, snapshots are written to file. 
* State handler interface remains the same, just the implementation behind it has changed
* The state handler now holds a map of states in-memory. The snapshot repository is only used to write snapshots to file (not read state from file for every read access)
* Reduce the amount of snapshots kept to 4
* Removes the `ita-sgx-runtime` dependency in the state handler
* Increase the peer block fetching buffer size from 128 KB to 256 KB
* We still have file i/o on every state write - this will be improved in a next PR, when we introduce the concept of a finalized state (as a result we will only write finalized state snapshots to file)
* In contrast to what #459 suggests, we don't write snapshots asynchronously. …

Keep state in-memory, write snapshots to file

---

core-primitives/stf-executor/src/executor.rs
core-primitives/stf-executor/src/executor_tests.rs
core-primitives/stf-executor/src/traits.rs
core-primitives/stf-state-handler/src/handle_state.rs
core-primitives/stf-state-handler/src/state_handler.rs
core-primitives/stf-state-handler/src/test/sgx_tests.rs
core-primitives/test/src/mock/handle_state_mock.rs
core-primitives/top-pool-author/src/author_tests.rs
docker/docker-compose.yml
enclave-runtime/src/initialization/global_components.rs
enclave-runtime/src/test/mocks/types.rs
enclave-runtime/src/test/sidechain_aura_tests.rs
enclave-runtime/src/test/sidechain_event_tests.rs
enclave-runtime/src/test/tests_main.rs
enclave-runtime/src/tls_ra/seal_handler.rs
sidechain/block-composer/src/block_composer.rs
sidechain/consensus/aura/src/block_importer.rs
sidechain/consensus/aura/src/slot_proposer.rs
sidechain/consensus/aura/src/test/block_importer_tests.rs
sidechain/consensus/aura/src/verifier.rs
sidechain/consensus/common/src/block_import.rs
sidechain/consensus/common/src/test/mocks/block_importer_mock.rs
sidechain/state/src/impls.rs
sidechain/state/src/lib.rs

This is a follow-up refactoring for #459 
In our current design, we copy our state many times over during the regular workflow of producing sidechain blocks. Copying state is one of the performance bottlenecks, as our benchmarks have shown (once the state gets to MB size). This refactoring is a step towards reducing the amount of copying necessary.
* The sidechain state traits like `SidechainState` are now directly implemented by `SgxExternalities` instead of having a separate `SidechainDB` struct that requires moving in a state (which in turn required copying state).
* Removed `SidechainDB` as a result 
* Added a `execute_on_current` method to the state handler trait, which executes a function on a state reference without having to copy the state.
* Removed obsolete …

State handling refactoring: Reduce state cloning

---

service/src/main.rs
service/src/utils.rs

This PR gets rid of the need to create these two files when they won't be used.

Skip spid/ra_api_key files if `--skip-ra` is active

---

local-setup/py/helpers.py

We recently removed the condition that those files need to be present in the rust code because they are not needed if we don't perform the remote attestation: https://github.com/integritee-network/worker/pull/1116
However, this part was missed in the local setup. This fixes it, and simply prints a small warning that remote attestation is not possible when those files are not present.

[local-setup] ignore if key.txt and spid.txt are not found

---

Cargo.lock
app-libs/stf/src/lib.rs
core-primitives/stf-executor/Cargo.toml
core-primitives/stf-executor/src/enclave_signer.rs
core-primitives/top-pool-author/src/author.rs
core-primitives/top-pool-author/src/mocks.rs
core-primitives/top-pool-author/src/traits.rs
enclave-runtime/Cargo.lock
enclave-runtime/src/initialization/global_components.rs
enclave-runtime/src/initialization/parentchain/common.rs
enclave-runtime/src/test/enclave_signer_tests.rs
enclave-runtime/src/test/tests_main.rs
enclave-runtime/src/test/top_pool_tests.rs

resolves #1084 
This PR tries to take the pending tx into consideration when computing the nonce in `StfEnclaveSigner::sign_call_with_self`, it's based on https://github.com/litentry/tee-worker/pull/123/files#diff-b45d7f9d388a23fd97f42304612c00c9ea1205f05fc1e8bcc41439effa02406b
We do have a testcase [here](https://github.com/litentry/tee-worker/commit/887a6252e9e05e863f1e9e34e611b5df84fc1046) but I'm not sure if it's worth integrating it here (as it introduces additional CI steps/ymls).

Adjust nonce in StfEnclaveSigner based on pending tx

---

Cargo.lock
app-libs/stf/Cargo.toml
app-libs/stf/src/lib.rs
app-libs/stf/src/stf_sgx.rs
app-libs/stf/src/stf_sgx_tests.rs
app-libs/stf/src/trusted_call.rs
core-primitives/stf-executor/src/executor.rs
core-primitives/stf-interface/Cargo.toml
core-primitives/stf-interface/src/lib.rs
core-primitives/stf-interface/src/mocks.rs
enclave-runtime/Cargo.lock
enclave-runtime/src/test/enclave_signer_tests.rs
enclave-runtime/src/test/evm_pallet_tests.rs
enclave-runtime/src/test/tests_main.rs

Currently the callback call-indexes in trusted call execution are always encoded as `unshield_funds_fn: [u8; 2]`: https://github.com/integritee-network/worker/blob/98e151adbb83d49c9f1204d23520fc71620d8c71/core-primitives/stf-interface/src/lib.rs#L53-L57
It makes it hard to extend when we want more calls to the parentchain and/or pallets other than teerex - we have such needs already.
This PR uses a more generic and extensible `node_metadata_repo` to replace the hardcoded one.

Avoid hardcoded call index when executing trusted calls

---

.github/workflows/build_and_test.yml

See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-not-requiring-successful-dependent-jobs for details.

GHA: always run integration-tests even if unit tests failed

---

Cargo.lock
app-libs/sgx-runtime/Cargo.toml
app-libs/stf/Cargo.toml
cli/Cargo.toml
enclave-runtime/Cargo.lock
service/Cargo.toml

I think it is better to pin our integritee-pallets and integritee-node dependencies to the branches to prevent potential build errors after a cargo update.

fix potential polkadot-v0.9.37 dependency leak after cargo update

---

.github/workflows/build_and_test.yml
Cargo.lock
Dockerfile
build.Dockerfile
docker/README.md
docker/demo-direct-call.yml
docker/demo-indirect-invocation.yml
docker/demo-sidechain.yml
docker/demo-smart-contract.yml
docker/demo-teeracle-generic.yml
docker/demo-teeracle.yml
docker/docker-compose.yml
docker/fork-inducer.yml
docker/sidechain-benchmark.yml

This PR replaces `dockerize` with docker [healthcheck](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck), reasons:
- a built-in functionality of docker, thus more standard and doesn't rely on third-party services
- better control over retrying/intervals
- better integration with docker view (logs/inspect)
It uses `nc` to test the availability of the node and `curl` to test the workers.

Replace dockerize with built-in healthcheck

---

service/src/worker.rs

This is a minor PR that originates from https://github.com/litentry/litentry-parachain/issues/1124#issuecomment-1367690264
When searching peers, it shouldn't error out when some peer is unreachable.

Do not error out when searching peers

---

.github/workflows/build_and_test.yml
app-libs/stf/src/stf_sgx_tests.rs
enclave-runtime/src/test/enclave_signer_tests.rs
enclave-runtime/src/test/tests_main.rs

The CI allowed other test case failures beside the teeracle one, which went unnoticed for a while.
This PR
- Fixes the tests
- Disables only the failing teeracle test case (which needs further investigation).
Only the teeracle related integration test should fail, please do not merge it if others fail.

Fix tests and CI

---

build.Dockerfile

This PR aims to decrease the docker image size. This should not break anything.
Currently integritee-service gets linked to the following SGX (/DCAP) related libraries:
```bash
ldd ./integritee-service | grep -E "dcap|sgx"
libsgx_urts_sim.so => /opt/sgxsdk/sdk_libs/libsgx_urts_sim.so (0x00007fb804482000)
libsgx_dcap_ql.so.1 => /lib/x86_64-linux-gnu/libsgx_dcap_ql.so.1 (0x00007fb804294000)
libsgx_dcap_quoteverify.so.1 => /lib/x86_64-linux-gnu/libsgx_dcap_quoteverify.so.1 (0x00007fb80406b000)
libdcap_quoteprov.so.1 => /lib/x86_64-linux-gnu/libdcap_quoteprov.so.1 (0x00007fb803ec3000)
libsgx_uae_service_sim.so => /opt/sgxsdk/sdk_libs/libsgx_uae_service_sim.so (0x00007fb803b52000)
libsgx_qe3_logic.so => /lib/x86_64-linux-gnu/libsgx_qe3_logic.so (0x00007fb8037c0000)
libsgx_pce_logic.so.1 => …
```

Reduce docker image size

---

Makefile
enclave-runtime/src/attestation.rs
service/src/main.rs

This PR contains some fixes (match expression, poll time) that should have been in #1159.
Should the 
```rust
trace!(" [Enclave] Compose register enclave got call: {:#?}", &call);
```
log stay? It is not the actual quote that is logged here.
If so, I will format it to print it in hex as we have discussed @clangenb.
---
Just to make sure that the DCAP related things get compiled I temporarily added the dcap flag into the Makefile, this will be reverted once the CI ran.

Marblerun prometheus integration fixes

---

sidechain/consensus/common/src/header_db.rs
sidechain/consensus/common/src/is_descendant_of_builder.rs
sidechain/consensus/common/src/lib.rs
sidechain/consensus/common/src/test/mocks/block_import_queue_worker_mock.rs

I tested that it builds and `cargo test -p its-consensus-common` passes.

Minor fixes for `is_descendant_builder`

---

.github/workflows/build_and_test.yml
.github/workflows/delete-release.yml
.github/workflows/label-checker.yml
.github/workflows/publish-docker-release.yml
.github/workflows/publish-draft-release.yml
Dockerfile
build.Dockerfile

Question: 
- I saw some `runs-on: ubuntu-latest` parameters, should I leave them as is, or set the version explicitly there as well?

Bump `integritee-dev` image, switch to Ubuntu 22.04 Jammy

---

service/src/main.rs

Previously if the feature `dcap` was enabled then the `integritee-service` would crash if it could not fetch Marblerun events:
```bash
Custom("Failed to fetch marblerun prometheus events from: http://localhost:9944/, error: Error: IO error"
```
This PR addresses this issue.

service: handle not running Marblerun Prometheus metrics server more gracefully

---

.github/workflows/build_and_test.yml

This action only runs when `clippy` or `taplo/cargo fmt` steps fail, that is why it is hard to encounter the deprecation warning.
See https://github.com/integritee-network/worker/actions/runs/4434784169 for a recent failure.

gha: Node.js 12 depracation, bump cancel-action

---

core-primitives/utils/src/hex.rs
sidechain/consensus/common/src/is_descendant_of_builder.rs

During the attesteer testing I found this bug, where if the input was an empy file (from the cli), then the worker (integritee-service) would crash.
This PR fixes that and adds a test case as well.
```
thread '<unnamed>' panicked at 'range end index 2 out of range for slice of length 0', core-primitives/utils/src/hex.rs:61:8
fatal runtime error: failed to initiate panic, error 5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Sgx(SGX_ERROR_ENCLAVE_CRASHED)', service/src/main.rs:391:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I also found a warning when running `cargo test --all`, fixed it as well.

Fix unchecked indexing in decode_hex

---

.github/workflows/build_and_test.yml
app-libs/oracle/src/oracle_sources/coin_gecko.rs
app-libs/oracle/src/oracles/exchange_rate_oracle.rs
core/rest-client/src/http_client.rs

This is the split off commit from #1222 as that PR is not yet ready to be merged (RA should be added as well).
EDIT: I also realized that the unit test passed on the `sgx_runner` branch because it is much faster than the default GHA Runner. I tested it with my laptop as well and sometimes 3 seconds were not enough for the request to run, resulting in `HttpReqError(IO(OS(WouldBlock))` error.
Fixes #1221.

GHA: fix teeracle failure by increasing the update interval of the API

---

.github/workflows/build_and_test.yml
core-primitives/attestation-handler/src/attestation_handler.rs
service/src/main.rs

As I was testing the different attestations I stumbled upon two small issues:
- DCAP attestation and `--skip-ra` flag did not work together, because `generate_dcap_ra_quote()`  returned an empty quote in case the skip_ra is specified, however the `extract_tcb_info_from_raw_dcap_quote()` function needs a valid quote, so it would fail.
The current solution is rather a workaround, I think it would make sense to open a new issues about the `--skip-ra` handling.
- EPID attestation: if the linkability of the quote and subscription does not match, then the API responds with `400, Bad request` as the [documentations](https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf) says:
>In case the Service Provider registered with a linkable EPID signature policy but uses
unlinkable …

Better error logs for remote attestation + make skip_ra work for dcap

---

service/src/teeracle/mod.rs

Teeracle: have updates run at start as well

---

core/offchain-worker-executor/src/executor.rs
core/parentchain/block-importer/src/block_importer.rs
core/parentchain/light-client/src/concurrent_access.rs
core/parentchain/light-client/src/error.rs
core/parentchain/light-client/src/io.rs
core/parentchain/light-client/src/lib.rs
core/parentchain/light-client/src/light_validation.rs
core/parentchain/light-client/src/light_validation_state.rs
core/parentchain/light-client/src/mocks/validator_mock.rs
core/parentchain/light-client/src/mocks/validator_mock_seal.rs
core/parentchain/light-client/src/state.rs
enclave-runtime/src/initialization/parentchain/parachain.rs
enclave-runtime/src/initialization/parentchain/solochain.rs
enclave-runtime/src/top_pool_execution.rs

Preliminary simplifications for #1081, which also helps with #1242.
* Remove `RelayId` of the light-client, we are going to support multiple parentchains differently; by instantiating multiple light-clients altogether.
* Instead of constructing and and setting the relay state-step separately, we set up the light-validation in the constructor exclusively now. This simplifies the code in various places.
* Don't read from disk when we execute on the validator state. The state is behind a global `RwLock`, there is no chance that the state on disk is more up-to-date than the one in memory.

Minor light-client refactor

---

core-primitives/stf-executor/src/executor_tests.rs
core/parentchain/indirect-calls-executor/src/executor.rs
core/parentchain/light-client/src/mocks/validator_mock.rs
core/parentchain/light-client/src/mocks/validator_mock_seal.rs
core/parentchain/test/src/lib.rs
core/parentchain/test/src/parentchain_block_builder.rs
core/parentchain/test/src/parentchain_header_builder.rs
enclave-runtime/src/test/sidechain_aura_tests.rs
enclave-runtime/src/test/sidechain_event_tests.rs
enclave-runtime/src/test/top_pool_tests.rs
service/src/tests/mocks/parentchain_api_mock.rs
service/src/tests/parentchain_handler_test.rs
sidechain/block-verification/src/lib.rs
sidechain/consensus/aura/src/lib.rs
sidechain/consensus/aura/src/test/block_importer_tests.rs
sidechain/consensus/common/src/peer_block_sync.rs
sidechain/consensus/slots/src/per_shard_slot_worker_tests.rs
sidechain/consensus/slots/src/slots.rs
sidechain/validateer-fetch/src/validateer.rs

I was bothered by setting up tests for the light-client-db in the other PR.

[itc-parentchain-test] better re-exports to simplify imports

---

Cargo.lock
cli/Cargo.toml
cli/src/base_cli/commands/balance.rs
cli/src/base_cli/commands/faucet.rs
cli/src/base_cli/commands/listen.rs
cli/src/base_cli/commands/shield_funds.rs
cli/src/base_cli/commands/transfer.rs
cli/src/base_cli/mod.rs
cli/src/benchmark/mod.rs
cli/src/commands.rs
cli/src/evm/commands/evm_call.rs
cli/src/evm/commands/evm_command_utils.rs
cli/src/evm/commands/evm_create.rs
cli/src/evm/commands/evm_read.rs
cli/src/evm/mod.rs
cli/src/lib.rs
cli/src/main.rs
cli/src/trusted_base_cli/commands/balance.rs
cli/src/trusted_base_cli/commands/nonce.rs
cli/src/trusted_base_cli/commands/set_balance.rs
cli/src/trusted_base_cli/commands/transfer.rs
cli/src/trusted_base_cli/commands/unshield_funds.rs
cli/src/trusted_base_cli/mod.rs
cli/src/trusted_cli.rs
cli/src/trusted_command_utils.rs
cli/src/trusted_operation.rs
cli/tests/basic_tests.rs

Hello,
Following up on https://github.com/integritee-network/worker/issues/1167 I have started a basic refactoring of the cli.
I needed to use `integritee-cli` from Android(and soon iOs) as a library so I cherry-picked and cleanup the required changes from our current branch and I am proposing this refactor.
NOTE: For this first draft, I aimed for the "minimal changeset" and not really for the "cleanest lib interface"... 
I am open for feedback!
Overview of the changes:
- most code from main.rs moved to lib.rs; with added structs `CliResultOk`, `CliError`, `CliResult`
- all `*Commands` return `CliResult`
- most of the logic changes are in `cli/src/trusted_operation.rs`
- `perform_trusted_operation` now return new struct `TrustedOpResult`
- I tried to correctly identify the previous "None …

integritee-cli: separate into library and binary

---

service/src/teeracle/mod.rs

Closes: #1291 
Is a quick fix but a more robust solution to address the underlying design is shown in: #1300

Comment out weather oracle start with fixit todo and gh issue

---

core-primitives/attestation-handler/Cargo.toml
enclave-runtime/Cargo.toml

The `production` flag did not make into the `itp-attestation-handler`, which resulted in using the wrong IAS URL in production mode.
Kudos to @mosonyi for helping with the investigation.
Closes https://github.com/integritee-network/worker/issues/1233.

Fix production feature propagation into the itp-attestation-handler

---

core-primitives/settings/src/lib.rs
core/parentchain/light-client/src/io.rs
core/parentchain/light-client/src/light_validation_state.rs
core/parentchain/light-client/src/state.rs
enclave-runtime/src/initialization/parentchain/parachain.rs
enclave-runtime/src/initialization/parentchain/solochain.rs
enclave-runtime/src/test/tests_main.rs
service/src/setup.rs

This is a bug that was introduced with #1288.
The problem was that `self.path().join(".1")` actually added a subdirectory instead of appending ".1" to the file name, which made the backup fail, as the subdirectory did not exist.
Other change:
* All the light-client files live in the `LIGHT_CLIENT_DB_PATH` directory now, instead of being individual files in the top-level directory. I think it is better domain-specific files are grouped in the same subdirectory to simplify file-management.

Fix backup of light-client db and introduce light-client-db subdirectory

---

cli/tests/basic_tests.rs
core-primitives/enclave-api/ffi/src/lib.rs
core-primitives/enclave-api/src/enclave_base.rs
enclave-runtime/Enclave.edl
enclave-runtime/src/lib.rs
local-setup/config/one-worker.json
local-setup/config/two-workers.json
service/src/cli.yml
service/src/config.rs
service/src/enclave/api.rs
service/src/main.rs
service/src/setup.rs
service/src/tests/commons.rs
service/src/tests/mocks/enclave_api_mock.rs
service/src/tests/mod.rs

* Closes #1292 
This breaks nothing because it falls back to the current behaviour to use the pwd if the flag is not defined. However, it will print a warning that this behaviour will change in the future because it makes more sense to default to a well-defined default data-directory somewhere on the user path. (Todo: create an issue about that)
Example command for teeracle:
```
./integritee-service --data-dir /tmp/teeracle run --dev --skip-ra
```
Files that reside in the `--data-dir` after starting it with the above command:
```bash
ls /tmp/teeracle/
aes_key_and_iv_sealed_data.bin  ed25519_key_sealed.bin  light_client_db.bin  rsa3072_key_sealed.bin  sidechain_db  
```
Note: Backing up the light-client data fails currently, but the bug is unrelated to this PR and is solved in #1333. We …

Introduce CLI for a configurable data-dir

---

service/src/main.rs

closes #1312
Quick hotfix to detect when an extrinsic can fail in `send_extrinsic`

Detect extrinsic failures on untrusted side

---

core-primitives/settings/src/lib.rs
service/src/config.rs
service/src/main.rs
service/src/teeracle/mod.rs
service/src/utils.rs

This pattern allows us to simplify default values and to coerce the fields into more ergonomic types.

[integritee-service] introduce getters for `RunConfig` and make fields private

---

core-primitives/settings/src/lib.rs
service/src/cli.yml
service/src/config.rs
service/src/main.rs
service/src/teeracle/interval_scheduling.rs
service/src/teeracle/mod.rs
service/src/teeracle/schedule_periodic.rs

* Closes #1344 
Reregistration can be configured with `--regegister 10s` for instance. The allowed values for the time interval are the same as for the `teeracle-update-interval`.

Reregister Teeracle after a CLI configurable period

---

.github/workflows/build_and_test.yml
.github/workflows/publish-draft-release.yml

We have decided to have 2 release functions
1. If the tag pattern is v[0-9]+.[0-9]+.[0-9]+ than it is an official release we publish both SDK and Docker releases
2. In case of any other: v[0-9]+.[0-9]+.[0-9]+-dev it will create a Docker release only.

Intermediate release won't make SDK release

---

docker/entrypoint.sh

Removed the debug message from docker entrypoint.

Remove debug message

---

build.Dockerfile

Failed because the latest semver compatible clap version 4.4.0 doesn't compile on rustc-1.6.8 any more (needs rustc-1.7.0). I have just put a `--locked` here because this is anyhow good practice for stability.

[GHA] fix sccache install failure

---

.github/workflows/build_and_test.yml
docker/README.md
docker/docker-compose.yml

This was actually a necessary fix, as our builder machine suddenly became outdated and was rejected by our node. Hence, the enclave couldn't register and the integration tests failed. The new node accepts outdated enclaves, but marks the enclave as outdated in the registry. Additionally, I increased the log levels so that we can actually observe why the enclave was rejected.

[GHA] bump integritee node to v1.1.3 and increase log levels

---

core/parentchain/block-importer/src/block_importer.rs
core/parentchain/light-client/src/io.rs
core/parentchain/light-client/src/lib.rs
core/parentchain/light-client/src/light_validation.rs
core/parentchain/light-client/src/light_validation_state.rs
core/parentchain/light-client/src/mocks/validator_mock.rs
core/parentchain/light-client/src/state.rs

This PR removes the parentchain tx-inclusion check, which didn't work. This led to an infinitely growing list of extrinsics with pending inclusion check in the light-client, which slowed down the block import tremendously. As the light-client was never the correct place to do that, I just removed the feature, and added a tracking issue for proper re-introduction: #1457.
* Closes #1454.

[light-client] remove pending parentchain tx-inclusion check

---

sidechain/consensus/slots/src/slots.rs

I think I found out why we had a flaky yield next slot test, which was a combination of having a global `LastSlot` object, but parallel tests. Depending on the order of the tests, it could be a slot was yielded even though it shouldn't have. I ran the problematic test 15 times on my local machine, and it passed every time, and the CI was also green on the first try. Hence, I believe that it is fixed.
* Closes https://github.com/integritee-network/worker/issues/1343

[its-consensus-slots] fix flaky tests, which are due to parallelism

---

.github/workflows/build_and_test.yml

Fixing it by putting the individual tests into a matrix that runs them in parallel on different machines. This also reduces the total time to run those clippy tests (less than linearly though, as the subsequent tests partly benefited from the cargo cache of the test before).
* Closes #1464

[CI] refactor clippy tests and fix clippy CI OOM

---

.github/workflows/build_and_test.yml

Goal: build them in parallel, reduce space on GitHub Actions hosted runners, as they might run out of space.

[CI] build worker and client in separate jobs

---

core-primitives/rpc/src/lib.rs
core/direct-rpc-server/src/builders/rpc_response_builder.rs
core/direct-rpc-server/src/rpc_connection_registry.rs
core/direct-rpc-server/src/rpc_watch_extractor.rs
core/rpc-server/src/mock.rs

Node fails silently to send direct rpc request status updates if request's id type is `String`. Client hangs out waiting for more responses because of `do_watch: true`.
```
[2023-09-14T12:18:18Z WARN  itp_top_pool::watcher] failed to update connection state: InvalidConnectionHash
[2023-09-14T12:18:24Z WARN  itp_top_pool::watcher] failed to send status update to rpc client: InvalidConnectionHash, InSidechainBlock(0xe85176151f962568ec126d7c8dd30fcba106d35388093c39d4937b60e29c0a85)
```
According to JSON-RPC 2.0 spec field `id` can be of type String, Number, or NULL.
We [reported it and fixed](https://github.com/litentry/litentry-parachain/issues/2129) in Litentry repo.

support json-rpc request string id

---

core/parentchain/block-importer/src/block_importer.rs
core/parentchain/light-client/src/light_validation.rs
enclave-runtime/src/lib.rs
service/src/main_impl.rs
service/src/parentchain_handler.rs

automatically init shard if primary worker and no shard exists onchain

---

Cargo.lock
app-libs/parentchain-interface/Cargo.toml
app-libs/parentchain-interface/src/integritee/mod.rs
app-libs/parentchain-interface/src/target_a/mod.rs
app-libs/parentchain-interface/src/target_b/mod.rs
cli/Cargo.toml
cli/src/base_cli/commands/faucet.rs
cli/src/base_cli/commands/shield_funds.rs
cli/src/base_cli/commands/transfer.rs
cli/src/command_utils.rs
cli/src/trusted_base_cli/commands/set_balance.rs
cli/src/trusted_base_cli/commands/transfer.rs
cli/src/trusted_base_cli/commands/unshield_funds.rs
cli/src/trusted_command_utils.rs
cli/src/trusted_operation.rs
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml
service/Cargo.toml
service/src/main_impl.rs
service/src/parentchain_handler.rs

it ended up being trivial to get rid of direct dependencies on L1 runtimes. This greatly shrinks the dependency tree, build time as well as adaptation trouble for downstream devs

got rid of runtime dependencies

---

Cargo.lock
enclave-runtime/Cargo.lock
sidechain/consensus/common/Cargo.toml
sidechain/consensus/common/src/block_import_queue_worker.rs
sidechain/consensus/common/src/lib.rs
sidechain/consensus/common/src/peer_block_sync.rs
sidechain/consensus/slots/src/lib.rs

closes #1544 
* sort queue by sidechain block number
* group blocks with same number and sort them by hash (deterministic ordering less likely to produce forks - compared to "prefer self-authored block")
* attempt to import in order and ignore failures, just try next candidate
the goal here is: even if a fork happens, each fork should continue producing blocks. Only then can finality be established on L1 and orphans can reliably be identified

more robust sidechain block import logic

---

.github/workflows/build_and_test.yml
Cargo.lock
app-libs/sgx-runtime/Cargo.toml
app-libs/stf/Cargo.toml
cli/Cargo.toml
core/parentchain/light-client/src/io.rs
enclave-runtime/Cargo.lock

I noticed that when preparing the raffle-demo that sgx-runtime doesn't build by itself in std, the reason was missing std enablement, I fixed it by removing the unnecessary dependencies whatsoever.

Fix ita-sgx-runtime standalone build and improve its Cargo.toml

---

.github/workflows/build_and_test.yml
.github/workflows/publish-docker-sidechain.yml
.github/workflows/publish-docker-teeracle.yml

This changes creates a cli docker image for teeracle and sidechain.

Added client to docker release

---

Cargo.lock
app-libs/parentchain-interface/Cargo.toml
cli/Cargo.toml
core-primitives/extrinsics-factory/Cargo.toml
core-primitives/node-api/api-client-extensions/Cargo.toml
core-primitives/node-api/api-client-types/Cargo.toml
core-primitives/types/Cargo.toml
enclave-runtime/Cargo.lock
service/Cargo.toml

since polkadot-sdk-1.7.0 the behavior of retracted tx has changed and we see them quite often now. As a quick hack, we just accept this tx status, but we will need to look deeper and handle potential side effects
See https://github.com/integritee-network/worker/issues/1589

fix retracted tx errors

---

build.Dockerfile

in the case where the docker building stage isn't cached on the builder, we need to pin sccache explicitly or it will complain about outdated rustc verison

fix CI if uncached

---

.github/workflows/build_and_test.yml
Cargo.lock
app-libs/parentchain-interface/Cargo.toml
cli/Cargo.toml
core-primitives/extrinsics-factory/Cargo.toml
core-primitives/node-api/api-client-extensions/Cargo.toml
core-primitives/node-api/api-client-types/Cargo.toml
core-primitives/types/Cargo.toml
docker/docker-compose.yml
enclave-runtime/Cargo.lock
local-setup/config/benchmark.json
local-setup/config/one-worker.json
local-setup/config/three-nodes-one-worker.json
local-setup/config/two-workers.json
service/Cargo.toml

Very simple PR that bumps the api-client and the integritee-test-node to a version supporting the `CheckMetadataHash` signed extension.
Note: This breaks the compatibility with nodes that don't have this signed extension. However, we deemed this to be reasonable, as probably every substrate chain wants this. Additionally, supporting a generic signed extension is on the roadmap for the future for the worker anyhow.

Support the `CheckMetadataHash` signed extension

---

Cargo.lock
app-libs/sgx-runtime/Cargo.toml
app-libs/sgx-runtime/pallets/parentchain/Cargo.toml
app-libs/sgx-runtime/pallets/parentchain/src/lib.rs
app-libs/sgx-runtime/pallets/parentchain/src/mock.rs
app-libs/sgx-runtime/pallets/parentchain/src/tests.rs
app-libs/sgx-runtime/pallets/parentchain/src/weights.rs
app-libs/stf/Cargo.toml
enclave-runtime/Cargo.lock

To simplify maintenance accross of different polkadot SDK versions, moving pallet-parentchain into this repository is more consistent.
related: https://github.com/integritee-network/pallets/pull/268

move pallet parentchain into this repo

---

Cargo.lock
app-libs/stf/Cargo.toml
app-libs/stf/src/getter.rs
app-libs/stf/src/helpers.rs
app-libs/stf/src/trusted_call.rs

Support verification of trusted calls and getters that have been signed by an extension-dapp injected signer. It also adds 2 test to verify that a trusted call/setter signed from the `@polkadot-js/extension-dapp` library are correctly verified.

Add support for trusted getter/calls that have been signed with an extension-dapp signer

---

cli/src/trusted_base_cli/commands/get_fingerprint.rs
cli/src/trusted_base_cli/commands/get_shard.rs

helpers for easier maintenance:
```
ubuntu@cbef50e3811c:~/worker/bin$ ./integritee-cli -U wss://scv1.paseo.api.incognitee.io -P 443 trusted get-fingerprint -x
5BUCG8UXdgjWDDFQUd5kuRwnubDnMFhYEdbgxDZTnrBx
0x3e1d4de8123172257f2dbeb9c37a6c0f05ac739bb2c3f29915b31741a8647687
ubuntu@cbef50e3811c:~/worker/bin$ ./integritee-cli -U wss://scv1.paseo.api.incognitee.io -P 443 trusted get-shard -xa
5wePd1LYa5M49ghwgZXs55cepKbJKhj5xfzQGfPeMS7c
0x496e636f676e69746565546573746e6574303030303030303030303030303033
IncogniteeTestnet000000000000003
```

allow hex output for get-shard and get-fingerprint

---

core-primitives/stf-executor/src/executor.rs

We have observed that TargetA and TargetB parentchain pallet instances never get an update even if the blocks are actually processed. this fixes it

fix setting parentchain pallet block processed storage for all targets

---

Cargo.lock
app-libs/parentchain-interface/src/event_subscriber.rs
cli/Cargo.toml
core-primitives/types/Cargo.toml
core-primitives/types/src/parentchain.rs
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml
service/Cargo.toml
service/src/main_impl.rs
service/src/ocall_bridge/component_factory.rs
service/src/ocall_bridge/worker_on_chain_ocall.rs

For easier incident response, the OCall Bridge logs encoded extrinsics as hex values into files in folders per parentchain within the working dir
Also, make service listen to events and log System::ExtrinsicFailed if might be relevant

log enclave extrinsics to parentchains

---

app-libs/stf/src/stf_sgx.rs
core-primitives/stf-interface/src/parentchain_pallet.rs
core-primitives/types/src/parentchain.rs
core/parentchain/light-client/src/concurrent_access.rs
core/parentchain/light-client/src/io.rs
core/parentchain/light-client/src/light_validation.rs
core/parentchain/light-client/src/mocks/validator_access_mock.rs
enclave-runtime/src/shard_creation_info.rs
service/src/main_impl.rs

trustless write of parentchain genesis hash into parentchain pallet in L2 runtime state upon shard init
bear in mind that starting 3 --dev nodes leads to the same genesis hash. 
```
./target/release/integritee-node --dev --unsafe-rpc-external --rpc-cors all
./target/release/integritee-node --rpc-port 9945 --dev --unsafe-rpc-external --rpc-cors all
./target/release/integritee-node --rpc-port 9946 --dev --unsafe-rpc-external --rpc-cors all
/integritee-service -u ws://172.17.0.1 -c --ws-external run --skip-ra --dev
./integritee-cli trusted --mrenclave $MRENCLAVE get-parentchains-info
ParentchainsInfo { 
integritee: ParentchainInfo { id: Integritee, genesis_hash: Some(0x6ca6d29ad6c4a200c4af356f74f03d6467dbc8a6e9ef225a2e672a990e1c7ead), block_number: Some(9), now: Some(1729792536000), …
```

init parentchain genesis hash

---

Cargo.lock
Cargo.toml
app-libs/parentchain-specs/Cargo.toml
app-libs/parentchain-specs/src/lib.rs
app-libs/stf/Cargo.toml
app-libs/stf/src/getter.rs
app-libs/stf/src/guess_the_number.rs
app-libs/stf/src/helpers.rs
app-libs/stf/src/lib.rs
app-libs/stf/src/trusted_call.rs
cli/demo_direct_call.sh
cli/demo_shielding_unshielding.sh
cli/demo_shielding_unshielding_using_shard_vault.sh
cli/demo_shielding_unshielding_using_shard_vault_on_target_a.sh
cli/demo_sidechain.sh
cli/src/benchmark/mod.rs
cli/test_auto_shielding_with_transfer_bob.sh
cli/test_shield_on_target_nodes_with_transfer_to_alice.sh
enclave-runtime/Cargo.lock
enclave-runtime/src/test/tests_main.rs

* STF fees are defined as fractions of a unit on L1
* units are derived by a hardcoded lookup from genesis hash to decimals

adjust fee to decimals by genesis and properly charge it before bumping nonce

---

cli/src/benchmark/mod.rs
cli/src/evm/commands/evm_call.rs
cli/src/evm/commands/evm_create.rs
cli/src/guess_the_number/commands/guess.rs
cli/src/guess_the_number/commands/push_by_one_day.rs
cli/src/guess_the_number/commands/set_winnings.rs
cli/src/trusted_base_cli/commands/set_balance.rs
cli/src/trusted_base_cli/commands/transfer.rs
cli/src/trusted_base_cli/commands/unshield_funds.rs
cli/src/trusted_operation.rs
core-primitives/rpc/src/lib.rs
core-primitives/types/src/lib.rs
core/direct-rpc-server/src/rpc_responder.rs
core/direct-rpc-server/src/rpc_watch_extractor.rs
local-setup/config/two-workers.json
sidechain/rpc-handler/src/direct_top_pool_api.rs

* tl;dr; we can subscribe to tops from the js now without any client workarounds. 🥳 Related PR: https://github.com/encointer/encointer-js/pull/116
* The crucial change was that websocket clients expect that the `result` of the first RPC response must only contain the subscription ID if it is a subscription, and nothing else. This ID will be used to match subsequent messages to the corresponding subscriptions.
* This also affected the client a little bit, but as the only `send_direct_request` use case is `author_submitAndWatchExtrinsic` currently this could be changed relatively easy. But this change hasn't been integrated holistically enough, we can improve the cli code in some places. Marked as a todo #1625.
* While implementing this, I noticed that our rpc-server doesn't really try to …

support json rpc 2.0 with `author_submitAndWatchExtrinsic` trusted calls

---

scripts/archive-yesterdays-logs.sh
scripts/crontab.example
scripts/snapshot-integritee-db.sh
scripts/snapshot-shards.sh
scripts/snapshot-target-a-db.sh

some helpful scripts which we may want to autodeploy
* take snapshots for recovery
* rsync nodes for potential hot-swap
* rollbacks possible on hourly basis
* hotswap: hourly sync, which means we could lose 1h of interactions
requires:
`apt install inotify-tools`

maintenance scripts

---

app-libs/sgx-runtime/pallets/notes/src/lib.rs
app-libs/sgx-runtime/pallets/notes/src/tests.rs
app-libs/sgx-runtime/src/lib.rs
app-libs/stf/src/helpers.rs
app-libs/stf/src/trusted_call.rs
cli/src/trusted_base_cli/commands/mod.rs
cli/src/trusted_base_cli/commands/note_bloat.rs
cli/src/trusted_base_cli/commands/waste_time.rs
cli/src/trusted_base_cli/mod.rs
core-primitives/stf-executor/src/executor.rs
core-primitives/stf-primitives/src/error.rs
sidechain/consensus/slots/src/lib.rs

for stress testing in the field in different dimensions. A permissioned account can call
* TrustedCall::note_bloat which inflates the state by storing a series of notes amounting to X kB
* TrustedCall::waste_time sleeps during execution for X ms
* fix a bug with the ringbuffer
* workaround a vulnerability that made the chain stall if a TOP causes overtime all by itself
```
curl localhost:8787/metrics | grep state_size
curl localhost:8787/metrics | grep after_aura
./integritee-cli trusted --direct --mrenclave $MRENCLAVE waste-time <mnemonic> 1900
./integritee-cli trusted --direct --mrenclave $MRENCLAVE note-bloat <mnemonic> 1024
./integritee-cli trusted --mrenclave $MRENCLAVE get-note-buckets-info
```
confirmed manually:
* sidechain block production continues even if waste_time is 1.9s
* …

add note bloat and waste time TrustedCalls and cli

---

service/src/main_impl.rs

closes #1647 
manual test: set timeout to 2 seconds:
```
[2024-11-12T15:26:08.428Z INFO  integritee_service::account_funding] [Integritee] Alice will grant 20744996371000 to 1051397465c70b7c658fb986a0b16665bc153c264831dedebb1c3d9cfb8ce0d9 (5CS6ka2D...)
[+] send extrinsic: bootstrap funding Enclave from Alice's funds
[2024-11-12T15:26:08.433Z WARN  substrate_api_client::rpc::tungstenite_client::client] Expected subscription, but received an id response instead: Object {"id": String("1"), "jsonrpc": String("2.0"), "result": String("e4NPrjgGNqg7aDEp")}
Task timed out after 2s
thread 'main' panicked at 'Extrinsic sending timed out. shutting down.', service/src/main_impl.rs:1090:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
q.e.d.

change nonce init to respect xt in tx pool

---

app-libs/stf/src/lib.rs
app-libs/stf/src/trusted_call.rs

..and default to 0.01 unless it's a permissioned call, then its zero

charge byte fees for notes

---

.github/workflows/build_and_test.yml
.github/workflows/publish-draft-release.yml

v3 is deprecated and is going to be removed on the 30.01.2025.

[ci] bump artifact actions to v4

---

Cargo.lock
cli/Cargo.toml
core-primitives/settings/src/lib.rs
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml
service/Cargo.toml
service/src/config.rs
service/src/main_impl.rs
service/src/setup.rs
service/src/tests/mod.rs
sidechain/storage/src/storage.rs

* run enclave tests in temporary subdir to avoid destroying actual state by running tests
* allow to protect shards and light-client db selectively even if `--clean-reset` is used
* automatically init shard if not present, even without `--clean-reset` 
bump 0.15.6

adjust clean reset logic

---

service/src/main_impl.rs
service/src/teeracle/mod.rs

a threading error lead to the worker being stuck in the update oracle loop without proceeding to serving metrics and listening to events on L1
CI has passed previously because the main functionality which is e2e tested was functional

fix teeracle threading

---

Cargo.lock
app-libs/stf/Cargo.toml
app-libs/stf/src/getter.rs
cli/src/trusted_base_cli/commands/get_undistributed_fees.rs
cli/src/trusted_base_cli/commands/mod.rs
cli/src/trusted_base_cli/mod.rs
enclave-runtime/Cargo.lock

Get the balance of the enclave signer which collets fees. Add uniform noise of 10x TX_FEE for recent caller privacy
testing:
```
decimals=10
tx fee: 100 000 000
execute 3x: ./integritee-cli trusted --shard HrAYWCwM9DCk4GYxzuJK9qa6QZVXgTsUxMXcmfxT8biZ get-undistributed-fees
35 639 820 615                                                                                                                                                                                                                                                                         
35 139 820 615                                                                                                                                                                
35 039 820 615
transfer until nonce = 8
36 039 820 615
36 739 820 615 …
```

implement PublicGetter undistributed_fees

---

cli/src/base_cli/commands/transfer.rs
core-primitives/types/src/xcm.rs

closes #1701 
We tested asset shielding against stable2412 which has XCMv5
This downgrades the Location type to XCMv4

downgrade to XCMv4 and fix cli native xfer on AssetHub

---

Cargo.lock
app-libs/assets-map/src/lib.rs
app-libs/stf/src/trusted_call.rs
cli/Cargo.toml
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml
service/Cargo.toml

only roughly. no price oracles used yet
also fixes bogus ETH location transformation from #1710
```
tester IncogniteeAHP account starts with 
L1: 0.003 ETH
shield 0.001 ETH
L1: 0.002 ETH
L2: 0.000998248686514887 ETH
send 0.0001 ETH to tester. received
L2: 0.000898248686514887
(fees were charged in DOT)
unshield 0.0005
L1: 0.0025 ETH
L2: 0.000398248686514887
Now testing if fees charged in ETH
send 0.0002 ETH to account without any DOT or other assets (tester2 local)
bal 0.0002
send 0.0001 back
bal 0.000094450000000000
fee 0.00000555 ETH
```

adjust fees per asset

---

Cargo.lock
app-libs/assets-map/src/lib.rs
app-libs/stf/src/trusted_call.rs
cli/Cargo.toml
enclave-runtime/Cargo.lock
enclave-runtime/Cargo.toml
service/Cargo.toml

https://etherscan.io/address/0x6982508145454ce325ddbe47a25d4ec3d2311933
* 18 decimals
* 0.0594$ today

add PEPE token
